### ISSUE TITLE
[bug] ViTune skipping songs like crazy

### ISSUE THREAD

**Issue by aRandomMenno** [25huizengek1/ViTune#516] opened 2024-10-25 11:56 UTC
### Steps to reproduce the bug

1. Install ViTune.
2. Play any song, (except already cached).
3. Get the error.

### Expected behavior

1. Install ViTune.
2. Listen to music.

### Actual behavior

1. Install ViTune.
2. Music doesn't play because of error.

Note: probably bc of yt api changes?
![Screenshot_20241025-134848](https://github.com/user-attachments/assets/c9e184e3-a123-4483-a8ba-491c982b61ba)

### ViTune version

r1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

android 15.0

### Device info

Pixel 7a, not rooted.

### Additional information

ADblocking DNS disabled, work profile active. Using islands (search on playstore).

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-10-25 12:00
Upgrade to the new version please, this has been fixed already. (Duplicate of #399)

(Turn of autoskip if you don't want to skip on error)

**Closed by 25huizengek1** 2024-10-25 12:00 UTC
Labels: bug
