### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by omarblack21** [25huizengek1/ViTune#361] opened 2024-06-22 08:41 UTC
## Feature request: ...

A clear and concise description of the feature you want to request.

Go To Artist , Refresh Quick Picks , Login or sign up, Animation in lyrics Like Spotify

**Comment by 25huizengek1** [comment] 2024-06-22 21:39
- Go to artist exists: click 'more from ...' or on the artist name to do so
- Quick picks don't have to refresh as they generally don't change on YouTube's side. When another song becomes trending on your local device, the UI updates accordingly automatically
- Login or sign up: duplicate of #199 
- Lyrics are already animated like Spotify. Switch to synchronized lyrics in the options menu in the bottom-right corner of the lyrics

**Closed by 25huizengek1** 2024-06-22 21:39 UTC
Labels: enhancement
