### ISSUE TITLE
Offline doesn't work for me 

### ISSUE THREAD

**Issue by Iahmedeid** [25huizengek1/ViTune#329] opened 2024-06-02 13:04 UTC
### Steps to reproduce the bug

When I listen to songs and save them offline, they are automatically deleted  

### Expected behavior

I want to fix that. I want to listen Offline 

### Actual behavior

.

### ViTune version

1.0.5

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

14

### Device info

Samsung A53 oneui 6.1

### Upstream reproducibility

Yes, this also happens with Vi music 
 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-06-02 16:38
This is too little information, I can't reproduce based on your issue.

1. Make sure your phone has enough storage.
2. Make sure your phone doesn't clear ViTune's cache memory (automatically)
3. Make sure ViTune's cache is not full, and make sure your cache size limit is high enough (Settings ==> Cache)
4. Provide logs of playing/starting a song

**Comment by Iahmedeid** [comment] 2024-06-08 11:55
What details do you need?

**Comment by MLGHerobrine** [comment] 2024-06-08 14:03
I had the same problem today. All my favorites which I cached yesterday were just gone. Only three songs were in my offline folder. After trying to pre-cache my favorites again, I had no songs in my offline folder. Downloading would not do anything. Upon setting my cache size to 2GB from unlimited just now, it is downloading again. This is probably an issue with unlimited cache. For reference, my phone has 750mb free.

**Comment by MLGHerobrine** [comment] 2024-06-08 18:53
Upon further testing, this seems to be a problem with the amount of songs pre-cached. At a certain point, it clears the entire cache when reloading the app. I am not sure what this point is, but it is greater than 200 songs.

**Comment by 25huizengek1** [comment] 2024-06-09 18:09
While ViTune has an 'unlimited' cache option, this is not **actually** "unlimited", because your OEM could limit an apps cache size, or clear it entirely. I think in this case Samsung's storage optimizer has something to do with this. Unfortunately, ViTune cannot solve these problems as they are entirely vendor-specific.

ViTune doesn't clear cache, unless you instruct it to do so manually. ViTune always tries to avoid data corruption by always using transactional queries on a sqlite database for the player cache, while storing all song data in separate files.

**Comment by genericbetatester** [comment] 2024-06-09 23:05
Now, most phones probably come with this "optimization apps" that claim to "clean" phone and all it does it clears app cache and the ram. If you have such apps on your phone, whenever the app does it's "optimization/cleaning" it clears app caches. That's probably what's happening to you.

**Comment by MLGHerobrine** [comment] 2024-06-10 13:02
I apologize for not providing my phone name earlier. I am on a Cat S22 Flip running Android 11 Go. I checked through my app list and found nothing that would delete my cache. Unless Android (possibly Go) has a feature that deletes your cache, this appears to be an issue with ViTune, at least on my end.

**Comment by xxpsychoo** [comment] 2024-06-10 15:16
This is the same issue with ViMusic. I feel that ViMusic is already excellent in many aspects. However, it has one drawback: it cannot be used offline. There is a pre-cache feature, but it is only temporary and then disappears.

And suddenly, ViTune arrived with a better interface and additional features compared to ViMusic.

I think ViTune would be perfect if it could introduce a download feature that is truly saved and does not disappear.

**Thank you in advance.**

**Comment by 25huizengek1** [comment] 2024-07-05 20:39
Closing this as this is not something that could be fixed by me (this is not an issue in ViTune's end)

@xxpsychoo the download functionality already works like that, but unfortunately issues arise for the same reason as described here: https://github.com/25huizengek1/ViTune/issues/329#issuecomment-2156723501

**Closed by 25huizengek1** 2024-07-05 20:39 UTC
Labels: bug
