### ISSUE TITLE
Album takes too long to load and you could get Unknown or Null info too

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#280] opened 2024-05-11 07:33 UTC
### Steps to reproduce the bug

1. Go to any randomly album
2. Wait

### Expected behavior

Album should load fast as always

### Actual behavior

Album information could load (Just Title & Thumbnail)
Album will probably shows for less than one second 'Unknown' as title and start 'loading' the title and thumbnail twice
Album could load every info, but for some reason, the screen goes to 'loading scenary' and its very slow
Album will takes too long to load every info from the screen.

It doesnt matter if its your first time using the app, you can also have a stable database, but still getting this problem

### Screenshots/Screen recordings

![image](https://github.com/25huizengek1/ViTune/assets/1917871/eb3dd2bb-50e7-4aa3-8139-813a58266085)
![image](https://github.com/25huizengek1/ViTune/assets/1917871/a3fe39c4-af23-4b90-9d02-4a727b827cb0)
![image](https://github.com/25huizengek1/ViTune/assets/1917871/e4f434a1-22ca-4efe-8811-857469e72b28)

![image](https://github.com/25huizengek1/ViTune/assets/1917871/dfd7298f-1209-485d-bd05-32949eb6a15e)
![image](https://github.com/25huizengek1/ViTune/assets/1917871/cdd5cc78-9759-4ba5-a3bc-56205b471f22)

### ViTune version

1.0.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Running Android 10 on Pixel 3a XL

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by siggi1984** [comment] 2024-05-11 09:32
> ### Steps to reproduce the bug
> 
>     1. Go to any randomly album
> 
>     2. Wait
> 
> 
> ### Expected behavior
> 
> Album should load fast as always
> ### Actual behavior
> 
> Album information could load (Just Title & Thumbnail) Album will probably shows for less than one second 'Unknown' as title and start 'loading' the title and thumbnail twice Album could load every info, but for some reason, the screen goes to 'loading scenary' and its very slow Album will takes too long to load every info from the screen.
> 
> It doesnt matter if its your first time using the app, you can also have a stable database, but still getting this problem
> ### Screenshots/Screen recordings
> 
> ![image](https://private-user-images.githubusercontent.com/1917871/329763139-eb3dd2bb-50e7-4aa3-8139-813a58266085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjAxNTgsIm5iZiI6MTcxNTQxOTg1OCwicGF0aCI6Ii8xOTE3ODcxLzMyOTc2MzEzOS1lYjNkZDJiYi01MGU3LTRhYTMtODEzOS04MTNhNTgyNjYwODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDkzMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjVhNGE1M2ViMDhhYjQzOTNiMWFiYTUwOWU4ZjI0MGZjNmJmY2E5OTBlY2MxZjU4NWE1NWNhMTIwNzYwZDk3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hb2o0LSLlxCGQg3NEN_LCmtDKnA1o0sWqkSLbWq07i4) ![image](https://private-user-images.githubusercontent.com/1917871/329763187-a3fe39c4-af23-4b90-9d02-4a727b827cb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjAxNTgsIm5iZiI6MTcxNTQxOTg1OCwicGF0aCI6Ii8xOTE3ODcxLzMyOTc2MzE4Ny1hM2ZlMzljNC1hZjIzLTRiOTAtOWQwMi00YTcyN2I4MjdjYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDkzMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk1NmM0MjQxNTBiMzcyOGJmMDNlODg2NGY5YjE3ODk5YWNjNjJmYWZjODYwYTZiN2Y5NTllMDc1ZDM0ZWQzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MN2ISRR-18GZlTLHAbK8_c-c8E25U9wJgnGn4iXTRj0) ![image](https://private-user-images.githubusercontent.com/1917871/329763192-e4f434a1-22ca-4efe-8811-857469e72b28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjAxNTgsIm5iZiI6MTcxNTQxOTg1OCwicGF0aCI6Ii8xOTE3ODcxLzMyOTc2MzE5Mi1lNGY0MzRhMS0yMmNhLTRlZmUtODgxMS04NTc0NjllNzJiMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDkzMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JkMmM4MTY1YTQ2YzdkMDg1MDYyYTk4MjgyNTUzZTA5NDQ4NzU1NzgwYzI0MmY0NjlmOTUzZjk4MWIyNmE0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T4TzDJhuhxqGZ7mYJ8_LcpNTdYyFzacwBASTwpHTcH0)
> 
> ![image](https://private-user-images.githubusercontent.com/1917871/329763055-dfd7298f-1209-485d-bd05-32949eb6a15e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjAxNTgsIm5iZiI6MTcxNTQxOTg1OCwicGF0aCI6Ii8xOTE3ODcxLzMyOTc2MzA1NS1kZmQ3Mjk4Zi0xMjA5LTQ4NWQtYmQwNS0zMjk0OWViNmExNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDkzMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjUzNDQzNjgwODMyYmM3N2QxMWM2NTc4NWJjNzdkNzk1MzcxYmUwMDE4YmNjODY0NTlkZmVjNTA5NGVmZmM5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L8vK_JvRvma4mCR0by5lWWLlrB_o_BJEtp0RjiyfTZ4) ![image](https://private-user-images.githubusercontent.com/1917871/329763071-cdd5cc78-9759-4ba5-a3bc-56205b471f22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MjAxNTgsIm5iZiI6MTcxNTQxOTg1OCwicGF0aCI6Ii8xOTE3ODcxLzMyOTc2MzA3MS1jZGQ1Y2M3OC05NzU5LTRiYTUtYTNiYy01NjIwNWI0NzFmMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDkzMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDY0NTk5MDhjNzY0YWE0ZTU5OTcwYTNiZTYxNWJiMjg5ODNlMGE4ZjBiYTE5ZGRiZjkwNjFmZDdkMzU5NDQwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zgqvc9imOYV3hT7KIEU7YySN124UnlgLpESn7pZZdCk)
> ### Logs
> 
> _No response_
> ### ViTune version
> 
> 1.0.4
> ### What kind of build are you using?
> 
> Release (GitHub / F-Droid)
> ### Android version
> 
> Android 10
> ### Device info
> 
> Running Android 10 on Pixel 3a XL
> ### Upstream reproducibility
> 
> _No response_
> ### Additional information
> 
> _No response_
> ### Checklist
> 
>     * [x]  I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
> 
>     * [x]  I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
> 
>     * [x]  This issue has not been submitted already (this is not a duplicate of another issue)

I have the same problem

**Comment by 25huizengek1** [comment] 2024-05-11 10:56
Here we go again, #229

**Comment by 25huizengek1** [comment] 2024-05-11 10:56
Duplicate of #229

**Closed** 2024-05-11 10:56 UTC
Labels: bug, duplicate
