### ISSUE TITLE
A Great Idea!! 

### ISSUE THREAD

**Issue by JHype7** [25huizengek1/ViTune#623] opened 2024-12-12 15:05 UTC
## Feature request: ...
I have seen that when I add my YT Playlist there is no search button so it would be very useful and also a sort order button (if possible).Thank You for the app...It's of Great Help ....

**Comment by habnixzutun** [comment] 2024-12-12 17:38
Duplicate of #539 and #102 I guess

**Comment by 25huizengek1** [comment] 2024-12-15 20:56
Duplicate of #102

**Closed by 25huizengek1** 2024-12-15 20:56 UTC
Labels: enhancement
