### ISSUE TITLE
Cache keeps clearing out

### ISSUE THREAD

**Issue by divno** [25huizengek1/ViTune#379] opened 2024-07-04 22:33 UTC
### Steps to reproduce the bug

Unsure how to repeat but it clears out much more often then it used to, sometime the same day I download songs, it may be that I download a lot of songs at a time but it's strange

### Expected behavior

Cached songs stay for a few days

### Actual behavior

Cache clears within the same day or the next day

### ViTune version

v1.0.6

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Pixel 8 pro stock  OEM android

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by davidpkj** [comment] 2024-07-05 07:45
May not actually be a bug. Had the same issue and it turned out that because my storage was very full, android regularly went on a cleaning spree deleting various cached information from different apps.

I don't know if changing the cache size matters in this case. Since it's the system that decides to prune "irrelevant data" which happens to be caches, which happen to store your downloaded songs. For me it was as simple as moving a some media over to another storage device, clearing up device storage and the problem was gone.

Could you check your remaining system storage capacity?

**Comment by divno** [comment] 2024-07-05 16:27
Ah ok this makes sense, I'm up to 100 GB out of 128 if all songs are downloaded which is weird why it would start clearing so early but I guess I have to remove some stuff, thanks 🙏

**Comment by 25huizengek1** [comment] 2024-07-05 20:37
@divno Not a bug since the system could (as specified somewhere in Android's documentation) clear the cache whenever it wants. Mostly it's either your OEM's storage optimizer or full storage in general. 

This is not something that can be fixed by me. ViTune never clears the entire cache itself, my cache has been intact for approximately a year now without any data loss, for example.

**Comment by 25huizengek1** [comment] 2024-07-05 20:38
Full explanation: https://github.com/25huizengek1/ViTune/issues/329#issuecomment-2156723501

**Closed by 25huizengek1** 2024-07-05 20:37 UTC
Labels: bug
