### ISSUE TITLE
Google Account Sync Feature

### ISSUE THREAD

**Issue by RaulKong898** [25huizengek1/ViTune#478] opened 2024-10-17 00:40 UTC
Hello, I'm a big fan of your ViTune app and have a suggestion for a new feature. I'd love to see a sync feature that allows me to connect my Google account to ViTune. This would make it easier to save and access my preferences, playlists, and listening history across multiple devices.

 I believe this feature would be a valuable addition to ViTune and improve the user experience. Thank you for your time and consideration. 

Sincerely, Raul Popescu

Please also add a listening history mode and sync with YouTube Music.

**Comment by Wqttzicue** [comment] 2024-10-17 09:20
Are u sure you checked originality of Suggestion?
Its alrrady suggested #199

**Comment by 25huizengek1** [comment] 2024-10-21 22:15
Duplicate of #199

> Anyways https://github.com/25huizengek1/ViTune/issues/199 is on low priority, so just wait couple million years..
@Wqttzicue 😂 

I still don't have time to work on ViTune to work on medium/large-sized changes unfortunately 😞

**Closed by 25huizengek1** 2024-10-21 22:15 UTC
Labels: enhancement

**Comment by Wqttzicue** [comment] 2024-10-21 22:17
> Duplicate of #199
> 
> > Anyways https://github.com/25huizengek1/ViTune/issues/199 is on low priority, so just wait couple million years..
> 
> @Wqttzicue 😂 
> 
> I still don't have time to work on ViTune to work on medium/large-sized changes unfortunately 😞 

Thats fine, just fix critical bugs, and thats ok.
