### ISSUE TITLE
Loading in album page 

### ISSUE THREAD

**Issue by Jetliarm** [25huizengek1/ViTune#341] opened 2024-06-09 12:06 UTC
### Steps to reproduce the bug

1. Open the app
2. Click Artist
3. open album
4. loading 

### Expected behavior

very loading 

### Actual behavior

.

### Screenshots/Screen recordings

![Screenshot_20240609-085252](https://github.com/25huizengek1/ViTune/assets/171421185/8fe672ea-f54c-4567-a125-acc670b98a21)

### Logs

.

### ViTune version

1.0.5

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

android 11

### Device info

.

### Upstream reproducibility

.

### Additional information

.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-06-09 14:11
Duplicate of #229

**Closed by 25huizengek1** 2024-06-09 14:11 UTC
Labels: bug
