### ISSUE TITLE
Feature requests 

### ISSUE THREAD

**Issue by walker-11** [25huizengek1/ViTune#328] opened 2024-06-01 18:32 UTC
## Feature request: ...

![Screenshot_2024-06-02-00-00-02-698_com.zionhuang.music.jpg](https://github.com/25huizengek1/ViTune/assets/151006009/72f10501-ed24-4422-bf6c-5ab49ac6ce0a)

A Refresh Button and login to YouTube Music, This features are available in innerTune which is also written in kotlin

![Screenshot_2024-06-01-23-59-44-830_com.zionhuang.music.jpg](https://github.com/25huizengek1/ViTune/assets/151006009/974550ec-ef92-47d9-a0ab-48331c784e7e)

**Comment by 25huizengek1** [comment] 2024-06-01 18:58
Duplicate of #199

**Closed by 25huizengek1** 2024-06-01 18:58 UTC
Labels: enhancement
