### ISSUE TITLE
Fast Errored Song Skipping

### ISSUE THREAD

**Issue by H0M3BR3WMA5TER** [25huizengek1/ViTune#507] opened 2024-10-24 20:10 UTC
### Steps to reproduce the bug

Search any song, select any song from the search list 

### Expected behavior

It should play the song

### Actual behavior

It constantly and very rapidly skips through tracks, throwing notification errors for each song

### Screenshots/Screen recordings

Added in new note

### ViTune version

v1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Samsung Galaxy A15 SM-A155F/DSN
OneUI 6.1
Android Version 14

### Additional information

This is also occuring on playlists where songs are in the cache

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by H0M3BR3WMA5TER** [comment] 2024-10-24 20:22
https://github.com/user-attachments/assets/8503c4f9-4038-4578-8df3-e8c75c498bb7

**Comment by Wqttzicue** [comment] 2024-10-24 23:26
Finally oroginal issue, 
Ye im experiencing same sometimes

**Comment by 25huizengek1** [comment] 2024-10-24 23:35
Duplicate of #499

**Closed by 25huizengek1** 2024-10-24 23:35 UTC
Labels: bug
