### ISSUE TITLE
Problem with video ID

### ISSUE THREAD

**Issue by alpanakbar7** [25huizengek1/ViTune#514] opened 2024-10-25 03:29 UTC
### Steps to reproduce the bug

1. Play any music you never heard before

### Expected behavior

When play music i never heard before the music should play

### Actual behavior

What happened instead in the song cover this appeared the returned video id doesn't match the request one
![Screenshot_2024-10-25-10-22-38-04_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/321ac187-5e75-49d5-8335-b449d5fb7853)

### Screenshots/Screen recordings

![Screenshot_2024-10-25-10-22-38-04_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/ce2bd3c7-290f-4b4d-848d-45caaddf5339)

### ViTune version

v1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 11

### Device info

I am using realme C15 Snapdragon edition 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by JustRandomboy** [comment] 2024-10-25 03:42
Duplicate of #499

**Comment by 25huizengek1** [comment] 2024-10-25 09:13
Duplicate of #499

**Closed by 25huizengek1** 2024-10-25 09:13 UTC
Labels: bug
