### ISSUE TITLE
Request for a year Wrapped feature 

### ISSUE THREAD

**Issue by Skandesh2008** [25huizengek1/ViTune#615] opened 2024-12-10 03:02 UTC
YouTube music , Spotify , Google photos and even Duolingo has a year Wrapped feature ! It would be great if a year Wrapped feature is introduced in the next update , which includes basic stuff like most listened song , favorite artist , time listened and songs discovered . 
It would be great to share with friends and family and keep as a personal record or momento 
Ty

**Comment by dtomvan** [comment] 2024-12-11 09:33
+1. UI is hard, but the code would probably be trivial, just a few SQL queries as everything is in a local DB anyways. Maybe next year :)

**Comment by DaniloPedrazzi** [comment] 2024-12-11 13:26
I started doing this like a week ago, but get overloaded on my job. Maybe I can resume the feature

**Comment by Skandesh2008** [comment] 2024-12-11 13:31
> I started doing this like a week ago, but get overloaded on my job. Maybe I can resume the feature

That would be great 👍🏻!!!
Please try to finish it by the end of year and we all would love a wrapped by the end of the year 💯 
All the best 👍🏻

**Comment by 25huizengek1** [comment] 2024-12-15 20:58
I started working on some UI too. I've come to the conclusion that it's really hard to make something that actually looks good though.

**Comment by 25huizengek1** [comment] 2024-12-17 21:55
I actually forgot about @Wqttzicue's issue

Duplicate of #469

**Comment by 25huizengek1** [comment] 2024-12-17 21:56
I actually forgot about @Namra56's issue, duplicate of #530

**Closed by 25huizengek1** 2024-12-17 21:55 UTC
Labels: enhancement
