### ISSUE TITLE
Visual bug in interface

### ISSUE THREAD

**Issue by Steve2412** [25huizengek1/ViTune#638] opened 2024-12-17 00:39 UTC
### Steps to reproduce the bug

When system change automatically the colour of the system (dark and light mode)

### Expected behavior

Automtically chanfe without any problem

### Actual behavior

The interface dont change properly all the interface, require to kill the app to get all changes

### Screenshots/Screen recordings

![Screenshot_20241216_184550](https://github.com/user-attachments/assets/a66c122b-08a7-4bbf-93cc-e88102852db1)

### ViTune version

V 1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Samsung A54 5G

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-12-17 21:53
Duplicate of #469

**Closed by 25huizengek1** 2024-12-17 21:53 UTC
Labels: bug
