### ISSUE TITLE
Playlists don't download occasionally 

### ISSUE THREAD

**Issue by vedxp** [25huizengek1/ViTune#128] opened 2024-02-23 05:16 UTC
### Steps to reproduce the bug

1. Open any saved playlist
2. Click on the download button 

### Expected behavior

The playlist should start downloading normally.

### Actual behavior

Sometimes, the download doesn't starts, nothing happens upon clicking the download button at all.

Have to force close and reopen the app to get it working.

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/87353286/7f596d2f-eb69-47a6-8f29-6f7800795546

### ViMusic version

0.6.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

Motorola Moto G54 5G running MyUX, near stock Android

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [x] This issue has not been submitted already (this is not a duplicate of another issue)
- [ ] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by 25huizengek1** [comment] 2024-02-23 16:36
This is probably caused by Android's battery optimizations or when you're low on RAM. Can you please provide some logs?

**Comment by 25huizengek1** [comment] 2024-03-10 22:44
Any updates on this?

**Comment by vedxp** [comment] 2024-03-11 06:24
> Any updates on this? @vedxp

Even I'm unable to reproduce this from that day onwards.

Closing this issue for now, will re-open with proper logs if I do encounter the same again.

**Comment by vedxp** [comment] 2024-03-23 17:15
> Encountered the same again, and hopefully captured the logs:

[ViTune_Download_Crash.log](https://github.com/25huizengek1/ViTune/files/14733039/ViTune_Download_Crash.log)
[23_03-22-40-35_565.log](https://github.com/25huizengek1/ViTune/files/14733040/23_03-22-40-35_565.log)

Currently on ViTune stable release.

**Comment by 25huizengek1** [comment] 2024-03-24 19:08
Thank you for the logs. The errors come from ViTune, and are thrown when the OS killed the player service for some reason. The app can't recover from this, so the download just gets cancelled. I guess I can just add an error message?

**Comment by 25huizengek1** [comment] 2024-03-24 19:20
Added an error message, as well as logging the system error as that wasn't getting logged before.
Closing for now. If you are able to capture said system error I'm happy to reopen and investigate whether it's ViTune's fault.

**Closed** 2024-03-24 19:19 UTC
Labels: bug
