### ISSUE TITLE
Podcasts

### ISSUE THREAD

**Issue by CatGamer23** [25huizengek1/ViTune#576] opened 2024-11-20 16:00 UTC
## Feature request: ...
Exactly what the title says. Can we add a podcasts section in the search? I don't see any issues with it, unless the API is different for podcasts. We could probably just treat it like a extra long song. The only thing I'd add that would make it different is to replace the previous/next buttons with +/-30 seconds (or 10) for the lock screen widget.

**Comment by Wqttzicue** [comment] 2024-11-20 16:31
I like that

**Comment by 25huizengek1** [comment] 2024-11-20 20:45
Duplicate of #260

**Closed by 25huizengek1** 2024-11-20 20:45 UTC
Labels: enhancement
