### ISSUE TITLE
Feature Request: YouTube Account Integration for Accessing Playlists and Liked Songs

### ISSUE THREAD

**Issue by KalpeshXOfficial** [25huizengek1/ViTune#471] opened 2024-10-13 13:27 UTC
### Description:
I would like to propose adding an option to connect YouTube accounts within the app, allowing users to access their YouTube Music playlists, liked songs, and more directly from the app. This feature would function similarly to the SPMP app, offering users seamless access to their YouTube Music content.

### Suggested Functionality:
1. **Add YouTube Account**: Users can log into their YouTube (Google) account from the app.
2. **Access Playlists**: Once connected, users can:
   - View and play their **liked songs**.
   - Access their **created playlists**.
   - Play music from their **subscribed artist playlists**.
3. **Sync Playlists**: Automatically sync YouTube playlists and liked content, so users always have the latest version available in the app.
4. **Control from the App**: Enable playback control such as play, pause, skip, and volume adjustments for YouTube Music content within the app.
5. **Include in Next Update**: Request to add this feature in the next app update to enhance user experience and bring more functionality to the music section.

### Benefits:
- Users can access their YouTube Music content without switching apps.
- Streamlines music management by consolidating playlists and controls in one app.
- Similar functionality to the SPMP app, increasing user engagement and satisfaction.
- Encourages users to rely on the app as a central hub for their music streaming.

### Additional Information:
Ensure compliance with YouTube's API policies and terms of service when integrating this feature. The feature should be available in regions where YouTube Music is supported.

**Comment by 25huizengek1** [comment] 2024-10-13 19:19
Duplicate of #199

**Closed by 25huizengek1** 2024-10-13 19:19 UTC
Labels: enhancement
