### ISSUE TITLE
Issue when trying to pre-cache songs

### ISSUE THREAD

**Issue by CreeperTriste** [25huizengek1/ViTune#491] opened 2024-10-22 15:06 UTC
### Steps to reproduce the bug

When there's already pre-cached songs and I try to cache more songs

### Expected behavior

It should add the songs properly

### Actual behavior

It's loading indefinitely, not making any progress

### Logs

--------- beginning of main
[2024-10-22T10:54:57.700Z] Info (21039) .vitune.android - Using CollectorTypeCC GC.
[2024-10-22T10:54:57.705Z] Error (21039) .vitune.android - Not starting debugger since process cannot load the jdwp agent.
[2024-10-22T10:54:57.712Z] Debug (21039) ActivityThread - setConscryptValidator
[2024-10-22T10:54:57.712Z] Debug (21039) ActivityThread - setConscryptValidator - put
[2024-10-22T10:54:57.724Z] Debug (21039) CompatibilityChangeReporter - Compat change id reported: 171979766; UID 10719; state: ENABLED
[2024-10-22T10:54:57.834Z] Debug (21039) nativeloader - Configuring clns-4 for other apk /data/app/~~XB3tk9b_4gMiVl-LIV9asQ==/app.vitune.android-M2xoWrqwmNKh8VYzM-XEJg==/base.apk. target_sdk_version=35, uses_libraries=, library_path=/data/app/~~XB3tk9b_4gMiVl-LIV9asQ==/app.vitune.android-M2xoWrqwmNKh8VYzM-XEJg==/lib/arm:/data/app/~~XB3tk9b_4gMiVl-LIV9asQ==/app.vitune.android-M2xoWrqwmNKh8VYzM-XEJg==/base.apk!/lib/armeabi-v7a, permitted_path=/data:/mnt/expand:/data/user/0/app.vitune.android
[2024-10-22T10:54:57.842Z] Unknown (21039) GraphicsEnvironment - ANGLE Developer option for 'app.vitune.android' set to: 'default'
[2024-10-22T10:54:57.842Z] Unknown (21039) GraphicsEnvironment - ANGLE GameManagerService for app.vitune.android: false
[2024-10-22T10:54:57.843Z] Unknown (21039) GraphicsEnvironment - Neither updatable production driver nor prerelease driver is supported.
[2024-10-22T10:54:57.845Z] Debug (21039) NetworkSecurityConfig - No Network Security Config specified, using platform default
[2024-10-22T10:54:57.846Z] Debug (21039) NetworkSecurityConfig - No Network Security Config specified, using platform default
[2024-10-22T10:54:57.858Z] Debug (21039) OpenGLRenderer - RenderThread::requireGlContext()
[2024-10-22T10:54:57.859Z] Debug (21039) libMEOW  - meow new tls: 0xf0e80f40
[2024-10-22T10:54:57.859Z] Debug (21039) libMEOW  - meow reload base cfg path: na
[2024-10-22T10:54:57.859Z] Debug (21039) libMEOW  - meow reload overlay cfg path: na
[2024-10-22T10:54:57.859Z] Warning (21039) QT       - qt_process_init() called
[2024-10-22T10:54:57.859Z] Error (21039) QT       - [QT]file does not exist
[2024-10-22T10:54:57.859Z] Warning (21039) QT       - Support!!
[2024-10-22T10:54:57.860Z] Error (21039) QT       - [QT]file does not exist
[2024-10-22T10:54:57.860Z] Debug (21039) libMEOW  - applied 2 plugins for [app.vitune.android]:
[2024-10-22T10:54:57.860Z] Debug (21039) libMEOW  -   plugin 1: [libMEOW_gift.so]:
[2024-10-22T10:54:57.860Z] Debug (21039) libMEOW  -   plugin 2: [libMEOW_semaphore]:
[2024-10-22T10:54:57.873Z] Info (21039) DecorView - [INFO] isPopOver=false config=true
[2024-10-22T10:54:57.874Z] Info (21039) DecorView - updateCaptionType: isFloating=false isApplication=true hasWindowDecorCaption=false this=DecorView@bbe0a34[]
[2024-10-22T10:54:57.874Z] Debug (21039) DecorView - setCaptionType = 0, this = DecorView@bbe0a34[]
[2024-10-22T10:54:57.875Z] Info (21039) DecorView - getCurrentDensityDpi: from real metrics. densityDpi=300 msg=resources_loaded
[2024-10-22T10:54:57.876Z] Info (21039) DecorView - setWindowBackground: isPopOver=false color=ff08041d d=android.graphics.drawable.ColorDrawable@3d98dd2
[2024-10-22T10:54:57.886Z] Info (21039) MSHandlerLifeCycle - check: return. pkg=app.vitune.android parent=null callers=com.android.internal.policy.DecorView.setVisibility:4412 android.app.ActivityThread.handleResumeActivity:5476 android.app.servertransaction.ResumeActivityItem.execute:54 android.app.servertransaction.ActivityTransactionItem.execute:45 android.app.servertransaction.TransactionExecutor.executeLifecycleState:176 
[2024-10-22T10:54:57.886Z] Info (21039) MSHandlerLifeCycle - removeMultiSplitHandler: no exist. decor=DecorView@bbe0a34[]
[2024-10-22T10:54:57.888Z] Debug (21039) OpenGLRenderer - RenderThread::setGrContext()
[2024-10-22T10:54:57.890Z] Debug (21039) NativeCustomFrequencyManager - [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
[2024-10-22T10:54:57.892Z] Info (21039) DecorView - notifyKeepScreenOnChanged: keepScreenOn=false
[2024-10-22T10:54:57.896Z] Debug (21039) InsetsController - onStateChanged: InsetsState: {mDisplayFrame=Rect(0, 0 - 720, 1600), mDisplayCutout=DisplayCutout{insets=Rect(0, 45 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(272, 0 - 448, 45), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=720 displayHeight=1600 physicalDisplayWidth=720 physicalDisplayHeight=1600 density={1.875} cutoutSpec={M 0,0 H -88 V 45 H 88 V 0 H 0 Z} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=60, center=Point(60, 60)}, RoundedCorner{position=TopRight, radius=60, center=Point(660, 60)}, RoundedCorner{position=BottomRight, radius=60, center=Point(660, 1540)}, RoundedCorner{position=BottomLeft, radius=60, center=Point(60, 1540)}]}  mRoundedCornerFrame=Rect(0, 0 - 720, 1600), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(637, 0 - 720, 45) rotation=0}, mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][720,45], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,1600][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][45,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[675,0][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_MANDATORY_GESTURES, mFrame=[0,0][720,68], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_MANDATORY_GESTURES, mFrame=[0,1563][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-100000,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][720,45], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[100000,0][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,100000][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][720,45], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_TAPPABLE_ELEMENT, mFrame=[0,0][0,0], mVisible=true, mInsetsRoundedCornerFrame=false} } host=app.vitune.android/app.vitune.android.MainActivity from=android.view.ViewRootImpl.setView:1732
[2024-10-22T10:54:57.897Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - setView = com.android.internal.policy.DecorView@bbe0a34 TM=true
[2024-10-22T10:54:57.899Z] Info (21039) MSHandlerLifeCycle - removeMultiSplitHandler: no exist. decor=DecorView@bbe0a34[MainActivity]
[2024-10-22T10:54:57.955Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - performTraversals params={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030302
[2024-10-22T10:54:57.955Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   fl=81810100
[2024-10-22T10:54:57.955Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   pfl=12020040
[2024-10-22T10:54:57.955Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   vsysui=100
[2024-10-22T10:54:57.955Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   bhv=DEFAULT
[2024-10-22T10:54:57.955Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   fitSides= naviIconColor=0}
[2024-10-22T10:54:57.956Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - performTraversals mFirst=true windowShouldResize=true viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030302
[2024-10-22T10:54:57.956Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   fl=81810100
[2024-10-22T10:54:57.956Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   pfl=12020040
[2024-10-22T10:54:57.956Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   vsysui=100
[2024-10-22T10:54:57.956Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   bhv=DEFAULT
[2024-10-22T10:54:57.956Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] -   fitSides= naviIconColor=0}
[2024-10-22T10:54:57.962Z] Debug (21039) InsetsController - onStateChanged: InsetsState: {mDisplayFrame=Rect(0, 0 - 720, 1600), mDisplayCutout=DisplayCutout{insets=Rect(0, 45 - 0, 0) waterfall=Insets{left=0, top=0, right=0, bottom=0} boundingRect={Bounds=[Rect(0, 0 - 0, 0), Rect(272, 0 - 448, 45), Rect(0, 0 - 0, 0), Rect(0, 0 - 0, 0)]} cutoutPathParserInfo={CutoutPathParserInfo{displayWidth=720 displayHeight=1600 physicalDisplayWidth=720 physicalDisplayHeight=1600 density={1.875} cutoutSpec={M 0,0 H -88 V 45 H 88 V 0 H 0 Z} rotation={0} scale={1.0} physicalPixelDisplaySizeRatio={1.0}}}}, mRoundedCorners=RoundedCorners{[RoundedCorner{position=TopLeft, radius=60, center=Point(60, 60)}, RoundedCorner{position=TopRight, radius=60, center=Point(660, 60)}, RoundedCorner{position=BottomRight, radius=60, center=Point(660, 1540)}, RoundedCorner{position=BottomLeft, radius=60, center=Point(60, 1540)}]}  mRoundedCornerFrame=Rect(0, 0 - 720, 1600), mPrivacyIndicatorBounds=PrivacyIndicatorBounds {static bounds=Rect(637, 0 - 720, 45) rotation=0}, mSources= { InsetsSource: {mType=ITYPE_STATUS_BAR, mFrame=[0,0][720,45], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_NAVIGATION_BAR, mFrame=[0,1600][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_GESTURES, mFrame=[0,0][45,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_GESTURES, mFrame=[675,0][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_MANDATORY_GESTURES, mFrame=[0,0][720,68], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_MANDATORY_GESTURES, mFrame=[0,1563][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_LEFT_DISPLAY_CUTOUT, mFrame=[0,0][-100000,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_DISPLAY_CUTOUT, mFrame=[0,0][720,45], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_RIGHT_DISPLAY_CUTOUT, mFrame=[100000,0][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_DISPLAY_CUTOUT, mFrame=[0,100000][720,1600], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_TOP_TAPPABLE_ELEMENT, mFrame=[0,0][720,45], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_BOTTOM_TAPPABLE_ELEMENT, mFrame=[0,0][0,0], mVisible=true, mInsetsRoundedCornerFrame=false}, InsetsSource: {mType=ITYPE_IME, mFrame=[0,0][0,0], mVisibleFrame=[0,1510][720,1600], mVisible=false, mInsetsRoundedCornerFrame=false} } host=app.vitune.android/app.vitune.android.MainActivity from=android.view.ViewRootImpl.relayoutWindow:9802
[2024-10-22T10:54:57.963Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - updateBlastSurfaceIfNeeded mBlastBufferQueue=null isSameSurfaceControl=false
[2024-10-22T10:54:57.963Z] Debug (21039) BufferQueueConsumer - [](id:522f00000000,api:0,p:-1,c:21039) connect: controlledByApp=false
[2024-10-22T10:54:57.964Z] Info (21039) BLASTBufferQueue - new BLASTBufferQueue, mName= ViewRootImpl@a7d0f82[MainActivity] mNativeObject= 0xf3dd8700 sc.mNativeObject= 0xf0ee4a90 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 android.view.Choreographer.doCallbacks:923 android.view.Choreographer.doFrame:852 android.view.Choreographer$FrameDisplayEventReceiver.run:1283 
[2024-10-22T10:54:57.964Z] Info (21039) BLASTBufferQueue - update, w= 720 h= 1600 mName = ViewRootImpl@a7d0f82[MainActivity] mNativeObject= 0xf3dd8700 sc.mNativeObject= 0xf0ee4a90 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:84 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 
[2024-10-22T10:54:57.964Z] Error (21039) FBI      - Can't load library: dlopen failed: library "libmagtsync.so" not found
[2024-10-22T10:54:57.965Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)0 dur=7 res=0x3 s={true 0xf0c40000} ch=true seqId=0
[2024-10-22T10:54:57.965Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - mThreadedRenderer.initialize() mSurface={isValid=true 0xf0c40000} hwInitialized=true
[2024-10-22T10:54:57.966Z] Debug (21039) OpenGLRenderer - eglCreateWindowSurface
[2024-10-22T10:54:57.968Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - reportNextDraw android.view.ViewRootImpl.performTraversals:4438 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 
[2024-10-22T10:54:57.969Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - Setup new sync id=0
[2024-10-22T10:54:57.969Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - Setting syncFrameCallback
[2024-10-22T10:54:57.969Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - registerCallbacksForSync syncBuffer=false
[2024-10-22T10:54:57.980Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - Received frameDrawingCallback syncResult=0 frameNum=1.
[2024-10-22T10:54:57.980Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - Setting up sync and frameCommitCallback
[2024-10-22T10:54:57.980Z] Debug (21039) hw-ProcessState - Binder ioctl to enable oneway spam detection failed: Invalid argument
[2024-10-22T10:54:58.005Z] Info (21039) BLASTBufferQueue - [ViewRootImpl@a7d0f82[MainActivity]#0](f:0,a:0) onFrameAvailable the first frame is available
[2024-10-22T10:54:58.005Z] Info (21039) BLASTBufferQueue - [ViewRootImpl@a7d0f82[MainActivity]#0](f:0,a:1) acquireNextBufferLocked size=720x1600 mFrameNumber=1 applyTransaction=true mTimestamp=1331623038752600(auto) mPendingTransactions.size=0 graphicBufferId=90361816940546 transform=0
[2024-10-22T10:54:58.006Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
[2024-10-22T10:54:58.007Z] Debug (21039) OpenGLRenderer - CFMS:: SetUp Pid : 21039    Tid : 21055
[2024-10-22T10:54:58.009Z] Warning (21039) Parcel   - Expecting binder but got null!
[2024-10-22T10:54:58.009Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - onSyncComplete
[2024-10-22T10:54:58.009Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - setupSync seqId=0 mSyncId=0 fn=1 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503 
[2024-10-22T10:54:58.009Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - reportDrawFinished seqId=0 mSyncId=-1 fn=1 mSurfaceChangedTransaction=0xf0ffd5a0
[2024-10-22T10:54:58.016Z] Info (21039) ExoPlayerImpl - Init e6d9683 [AndroidXMedia3/1.4.1] [a13x, SM-A136W, samsung, 33]
[2024-10-22T10:54:58.041Z] Debug (21039) CompatibilityChangeReporter - Compat change id reported: 160794467; UID 10719; state: ENABLED
[2024-10-22T10:54:58.097Z] Debug (21039) ConnectivityManager - StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4402)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4444)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4826)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4796)] [W1.f.<init>(SourceFile:21)] [K4.l.a(SourceFile:44)] [u3.s.o(SourceFile:45)] [C4.h.b(SourceFile:148)] [C4.g.k(SourceFile:38)] [T6.a.n(SourceFile:9)] [q7.I.run(SourceFile:113)] [H5.g.run(SourceFile:32)] [x7.j.run(SourceFile:3)] [x7.a.run(SourceFile:96)]
[2024-10-22T10:54:58.104Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - MSG_WINDOW_FOCUS_CHANGED 1 0
[2024-10-22T10:54:58.104Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xf0c40000}
[2024-10-22T10:54:58.105Z] Debug (21039) InputMethodManager - startInputInner - Id : 0
[2024-10-22T10:54:58.105Z] Info (21039) InputMethodManager - startInputInner - mService.startInputOrWindowGainedFocus
[2024-10-22T10:54:58.123Z] Debug (21039) InputMethodManager - startInputInner - Id : 0
[2024-10-22T10:54:58.142Z] Debug (21039) libMEOW  - meow new tls: 0xedb54380
[2024-10-22T10:54:58.142Z] Debug (21039) libMEOW  - applied 2 plugins for [app.vitune.android]:
[2024-10-22T10:54:58.142Z] Debug (21039) libMEOW  -   plugin 1: [libMEOW_gift.so]:
[2024-10-22T10:54:58.142Z] Debug (21039) libMEOW  -   plugin 2: [libMEOW_semaphore]:
[2024-10-22T10:54:58.151Z] Debug (21039) libMEOW  - meow new tls: 0xd9e72240
[2024-10-22T10:54:58.151Z] Debug (21039) libMEOW  - applied 2 plugins for [app.vitune.android]:
[2024-10-22T10:54:58.151Z] Debug (21039) libMEOW  -   plugin 1: [libMEOW_gift.so]:
[2024-10-22T10:54:58.151Z] Debug (21039) libMEOW  -   plugin 2: [libMEOW_semaphore]:
[2024-10-22T10:54:58.151Z] Debug (21039) libMEOW  - meow new tls: 0xd9e62440
[2024-10-22T10:54:58.151Z] Debug (21039) libMEOW  - meow new tls: 0xd9e52300
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  - applied 2 plugins for [app.vitune.android]:
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  -   plugin 1: [libMEOW_gift.so]:
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  -   plugin 2: [libMEOW_semaphore]:
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  - meow new tls: 0xd9e5ac80
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  - applied 2 plugins for [app.vitune.android]:
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  -   plugin 1: [libMEOW_gift.so]:
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  -   plugin 2: [libMEOW_semaphore]:
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  - applied 2 plugins for [app.vitune.android]:
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  -   plugin 1: [libMEOW_gift.so]:
[2024-10-22T10:54:58.152Z] Debug (21039) libMEOW  -   plugin 2: [libMEOW_semaphore]:
[2024-10-22T10:54:59.874Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - ViewPostIme pointer 0
[2024-10-22T10:54:59.921Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - ViewPostIme pointer 1
[2024-10-22T10:55:00.688Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - ViewPostIme pointer 0
[2024-10-22T10:55:00.742Z] Info (21039) ViewRootImpl@a7d0f82[MainActivity] - ViewPostIme pointer 1
[2024-10-22T10:55:00.767Z] Debug (21039) ConnectivityManager - StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4402)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4966)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4933)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4907)] [A0.b0.x(SourceFile:1)] [T7.n.m(SourceFile:55)] [f2.h.<init>(SourceFile:105)] [f2.o.onCreate(SourceFile:202)] [app.vitune.android.service.PrecacheService.onCreate(SourceFile:1)] [andro

### ViTune version

v1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

I am using a Samsung A13 running One UI 5.1

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-10-22 15:54
Duplicate of #477 (already fixed)

**Closed by 25huizengek1** 2024-10-22 15:54 UTC
Labels: bug
