### ISSUE TITLE
Saving songs

### ISSUE THREAD

**Issue by EugeniuszPRO** [25huizengek1/ViTune#641] opened 2024-12-17 15:46 UTC
## Feature request: Proper song saving

Add proper downloading songs so you can play songs while offline without worrying about closing the app and making all the offline songs disappearing

**Comment by DaniloPedrazzi** [comment] 2024-12-17 21:46
Desappearing offline songs when closing the app is not the expected behavior... Maybe you are experiencing a bug?

**Comment by 25huizengek1** [comment] 2024-12-17 21:48
Duplicate of #329

**Closed by 25huizengek1** 2024-12-17 21:48 UTC
Labels: enhancement
