### ISSUE TITLE
Pre cache indicator

### ISSUE THREAD

**Issue by TadeTorresMartin** [25huizengek1/ViTune#276] opened 2024-05-08 22:58 UTC
## Feature request: Pre cache indicator

When I download the pre-cache of a song to listen to offline, it is mixed with the other songs that do not have it. Also an "Offline Only" mode would be nice

**Comment by Enigma1309** [comment] 2024-05-09 07:06
> an "Offline Only" mode would be nice

dupe of #244 

> When I download the pre-cache of a song to listen to offline, it is mixed with the other songs that do not have it.

so you want an indicator that indicates whether a song has been fully cached? can you please elaborate it..

**Comment by genericbetatester** [comment] 2024-05-09 11:30
Does the "offline" playlist not perform the same function?

**Comment by 25huizengek1** [comment] 2024-05-09 13:59
The offline only part is a duplicate of #244 

I'm not going to separate things, because they are both cached songs, but the only difference is that the pre-cache button caches a song before playing, not while playing.

**Closed by 25huizengek1** 2024-05-09 13:59 UTC
Labels: enhancement

**Comment by TadeTorresMartin** [comment] 2024-05-10 17:36
> > an "Offline Only" mode would be nice
> 
> dupe of #244 
> 
> > When I download the pre-cache of a song to listen to offline, it is mixed with the other songs that do not have it.
> 
> so you want an indicator that indicates whether a song has been fully cached? can you please elaborate it..

![Screenshot_20240510-143347.jpg](https://github.com/25huizengek1/ViTune/assets/111647605/68a50e68-8c49-4704-9bde-98ef0c6db5e0)

In the screenshot I show in the album section some that I have saved and pre-cached but there is no way that I know of. While the offline playlist is useful, it is all together, there is no separation of artists or albums

**Comment by TadeTorresMartin** [comment] 2024-05-10 17:38
> .

Right I didn't see the offline playlist my bad. But using the playlist I see something uncomfortable. I can't multi select in the playlist for hide the swipe left to hide only works in songs tab
