### ISSUE TITLE
Pre Cache Download Album And Delete Button

### ISSUE THREAD

**Issue by Steve2412** [25huizengek1/ViTune#155] opened 2024-03-09 20:10 UTC
Is possible to add the option of download pre cache on playlist in albums? Also it would be nice add an option to remove the cache songs when you deleted a playlist/albums, to clear the cache automatically and save memory.

**Comment by 25huizengek1** [comment] 2024-03-10 22:22
Great suggestion, but unfortunately a duplicate of #93 so I'll continue the conversation over there.

**Closed by 25huizengek1** 2024-03-10 22:22 UTC
Labels: duplicate, enhancement
