### ISSUE TITLE
What's happening with my quick picks

### ISSUE THREAD

**Issue by uZiElkVn** [25huizengek1/ViTune#241] opened 2024-04-18 00:25 UTC
### Steps to reproduce the bug

1. Open ViTune

### Expected behavior

Quick picks should shows a lot of songs

### Actual behavior

Quick picks only shows 1 song

### Screenshots/Screen recordings

![Screenshot_20240418-070934](https://github.com/25huizengek1/ViTune/assets/138131765/df49d68c-dbff-40a4-bb1a-c0b1b7a5bd4e)

### ViTune version

1.0.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 11

### Device info

I am using Infinix, running XOS

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by FaqatZubair1** [comment] 2024-04-18 04:11
I have the same issue with the latest nightly version.
The dev will fix it, till then, use the stable version.

**Comment by 25huizengek1** [comment] 2024-04-18 06:20
Apparently, YouTube changed the way this works overnight. I'll have a look at this.

**Comment by 25huizengek1** [comment] 2024-04-18 06:21
Also reproducible on ViMusic v0.5.4

**Comment by 25huizengek1** [comment] 2024-04-18 06:29
I think YouTube Music just messed something up, because this doesn't work anymore, even on the official website.

**Comment by 25huizengek1** [comment] 2024-04-18 08:28
That is not the source for quick picks, ViTune uses the related tab from the player, because that is the only way to get suggestions for a specific song, without having to log in:

![404E5DD2-3A6C-4E7F-9ED7-403D2B0525D9](https://github.com/25huizengek1/ViTune/assets/50515369/3d807b59-3099-471c-bf69-40c039486265)

And as you can see, YouTube doesn’t show any results anymore for any song.
I think this is not intentional and it should get fixed on their part, but of course I could opt to use data from the home page from now on. This means that the layout of quick picks will have to adapt to the new data, and that quick picks doesn’t provide suggestions based on your history anymore. I guess we should just wait and see if YouTube fixes this.

**Comment by 25huizengek1** [comment] 2024-04-18 08:31
Apparently, only the website is messed up. Unfortunately, ViTune uses the endpoint for web, so that is the reason that this doesn’t work on web, but does work in the official app. This means I’ll have to reverse-engineer the app in order to understand the endpoint that the app uses.

**Comment by 25huizengek1** [comment] 2024-04-18 23:22
In order to mitigate this, I'm considering either removing quick picks for now, or using radio suggestions, which means there will only be a list of suggestions, but even that is better than nothing. YouTube should just fix this on their end, because their own web app is broken, but we'll see.

**Comment by 25huizengek1** [comment] 2024-04-19 05:48
Yes, but since you're not logged in when using ViTune, YouTube won't provide quick picks based on a song that ViTune provides.

I can implement something like this for now, but it won't have the best results...

It really seems YouTube is not aware of this, but we'll see.

**Comment by FaqatZubair1** [comment] 2024-04-19 07:17
> 
> It really seems YouTube is not aware of this, but we'll see.
We should all report this to YouTube. That their website has a bug. Right?

**Comment by 25huizengek1** [comment] 2024-04-20 01:20
YouTube fixed it, closing for hopefully forever

![Screenshot_20240420-031950.png](https://github.com/25huizengek1/ViTune/assets/50515369/7b1c251c-766b-420d-aa76-e4b3d37856fc)

**Closed by 25huizengek1** 2024-04-20 01:20 UTC
Labels: bug
