### ISSUE TITLE
"Returned video id doesn't match" bug retained from Vimusic

### ISSUE THREAD

**Issue by AlfieWaddington** [25huizengek1/ViTune#490] opened 2024-10-22 14:28 UTC
### Steps to reproduce the bug

Attempt to play song from any feed (Playlists or Songs tab)

### Expected behavior

Song plays

### Actual behavior

Returns error "The returned video id doesn't match the requested one"

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/7ec2e936-539f-4ecd-92fa-4ba06fe12c82

### ViTune version

v1.1.0-RELEASE

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 12

### Device info

Samsung Galaxy a51 running stock android

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-10-22 15:54
Duplicate of #477 (already fixed)

**Closed by 25huizengek1** 2024-10-22 15:54 UTC
Labels: bug
