### ISSUE TITLE
Album 

### ISSUE THREAD

**Issue by senolfndk** [25huizengek1/ViTune#323] opened 2024-05-30 02:06 UTC
Albums not visible ![Screenshot_20240530-050607.jpg](https://github.com/25huizengek1/ViTune/assets/52818836/0ebb9e84-a560-49ea-a88e-cebc50fda545)

**Comment by 25huizengek1** [comment] 2024-05-30 05:40
Duplicate of #229

**Closed by 25huizengek1** 2024-05-30 05:40 UTC
