### ISSUE TITLE
App crashes after importing database from external storage

### ISSUE THREAD

**Issue by NoMrBody** [25huizengek1/ViTune#557] opened 2024-11-09 09:38 UTC
### Steps to reproduce the bug

Settings -> database -> Restore
then choosing backed-up file and then app closes by itself.

### Expected behavior

opening the app with restored data

### Actual behavior

closing immediately after opening

### ViTune version

1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Samsung galaxy A55

### Additional information

I had this problem with my previous android phone.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-11-09 22:43
Duplicate of #268

**Closed by 25huizengek1** 2024-11-09 22:43 UTC
Labels: bug
