### ISSUE TITLE
Changing song position in playlist not working properly.

### ISSUE THREAD

**Issue by rikuf2** [25huizengek1/ViTune#200] opened 2024-03-30 14:11 UTC
### Steps to reproduce the bug

1. Put some random music to playlist and make sure there are at least 20
2. Try to rearrange the tracks in playlist
3. The tracks just snap back to their original position

### Expected behavior

It should keep the positions of the tracks and not snap back to their original position.

### Actual behavior

The tracks just snap back to their original position.

### ViTune version

v1.0.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Oneplus 8T running LineageOS 21 (Android14)
Samsung A14 running OneUI 6.0 (Android14)

### Additional information

I wasn't able to add any screen recording since the recordings are always over 10mb limit. 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by rikuf2** [comment] 2024-03-30 14:17
https://drive.proton.me/urls/6RES0RP9Q8#j6UleGlG9Clw

**Comment by rikuf2** [comment] 2024-03-30 14:17
Link to screen recording

**Comment by 25huizengek1** [comment] 2024-03-30 14:25
Seems like an invalid playlist, but a duplicate of #127 nonetheless.

**Closed by 25huizengek1** 2024-03-30 14:25 UTC
Labels: bug

**Comment by rikuf2** [comment] 2024-03-30 14:28
Would have been better if that issue was labeled as bug so I would have noticed it.
