### ISSUE TITLE
When release for Windows Version 😍😍

### ISSUE THREAD

**Issue by walker-11** [25huizengek1/ViTune#282] opened 2024-05-12 10:00 UTC
## Feature request: ...

Please make and release Vi Tune Windows Version 😍😍 Best music app so Far ❤️

**Comment by 25huizengek1** [comment] 2024-05-12 21:07
Thank you so much for your appreciation, unfortunately this is a duplicate of #190, so I'll have to close this.

**Closed** 2024-05-12 21:07 UTC
Labels: duplicate, enhancement
