### ISSUE TITLE
couldnt restore the data when selecting a .db file

### ISSUE THREAD

**Issue by nathn01** [25huizengek1/ViTune#554] opened 2024-11-05 13:22 UTC
### Steps to reproduce the bug

1. Open ViTune
2. Go to Settings
3. Go to Database
4. Click Restore
5. Select the file
6. After closing, open ViTune again

it should have restored my playlists :(

### Expected behavior

it shouldve restored my songs, playlist after restored it

### Actual behavior

it wouldnt let me restore my data 

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

11

### Device info

Vivo 1906

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment] 2024-11-05 13:50
Смартфон Vivo

**Comment by MLGHerobrine** [comment] 2024-11-05 13:50
I've had this happen before. Try a reloading different backup.

**Comment by dtomvan** [comment] 2024-11-08 10:18
Yeah over the months some db types (old vimusic, rimusic) have become incompatible. Not a lot to do about it but if you provide logs using adb logcat maybe we can help. https://stackoverflow.com/a/9727223

**Comment by 25huizengek1** [comment] 2024-11-20 21:12
Duplicate of #268

**Closed by 25huizengek1** 2024-11-20 21:12 UTC
Labels: bug

**Comment by awwRoar** [comment] 2024-12-30 10:57
Temporary workaround for v1.1.1 app foreclosure after importing db:
Import database to the app from external storage -> App crashes -> Switch off internet -> Open ViTune and go to the Local (last one) section -> Grant storage permission again if it prompts -> Switch to Songs / Playlists section to check if your db has been added (without thumbnails) -> Switch on internet -> End

This worked for me today.
