### ISSUE TITLE
Error while trying to play any song

### ISSUE THREAD

**Issue by lazaruswhite** [25huizengek1/ViTune#504] opened 2024-10-24 16:03 UTC
### Steps to reproduce the bug

1. Open the app. 
2. Try and play any song

### Expected behavior

The song should get played

### Actual behavior

Instead a error is shown saying "the returned video ID doesn't match the requested one" 

### Screenshots/Screen recordings

![Screenshot_2024-10-24-21-30-49-724_app vitune android](https://github.com/user-attachments/assets/aa67f3fc-6bdb-48fb-b0fa-42d4bd0970ca)

### ViTune version

v1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

I m using redmi 9A

### Upstream reproducibility

The same happened in Vimusic too

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Souravjyoti-Kalita** [comment] 2024-10-24 16:57
I am facing the same issue too

**Comment by MLGHerobrine** [comment] 2024-10-24 17:04
Piped is down, please wait. Duplicate issue.

**Comment by 25huizengek1** [comment] 2024-10-24 18:03
Duplicate of #499

**Closed by 25huizengek1** 2024-10-24 18:03 UTC
Labels: bug
