### ISSUE TITLE
Feature request: change song metadata

### ISSUE THREAD

**Issue by LogicForg** [25huizengek1/ViTune#533] opened 2024-10-29 10:15 UTC
Let us rename songs , change album covers and their artists for customisation, specially in local files.

I hope you all can implement this feature , would be real thankful 🙏🙏

**Comment by Wqttzicue** [comment] 2024-10-29 15:50
I Like that! I hope ingek will implement this

**Comment by Monoxide8969** [comment] 2024-10-30 10:29
I was sure this issue was a duplicate but apparently nobody has yet suggested it. That's great, I've wanted this feature for a long time

**Comment by LogicForg** [comment] 2024-11-05 17:57
Can it be added in the next update 🥺👉👈

**Comment by Wqttzicue** [comment] 2024-11-05 18:47
> Can it be added in the next update 🥺👉👈

No, this wont happen beacause this sugg isnt even on low:prio.

**Comment by 25huizengek1** [comment] 2024-12-01 12:21
Duplicate of #308 (my bad, just doing this on my phone right now)

**Closed by 25huizengek1** 2024-12-01 12:21 UTC
Labels: enhancement
