### ISSUE TITLE
 Please implement 'right swipe to play next' 

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViTune#397] opened 2024-07-30 14:00 UTC
https://github.com/user-attachments/assets/ff44f815-4a7c-4ee3-a774-062dab8a6de4

**Comment by 25huizengek1** [comment] 2024-07-30 14:47
Duplicate of #233

**Closed by 25huizengek1** 2024-07-30 14:47 UTC
Labels: enhancement

**Comment by siggi1984** [comment] 2024-07-30 15:29
Oh sorry I didn't see that.
