### ISSUE TITLE
Community Playlist And Albums Are Not Loading And Showing Nothing , and vi music Stopping In the middle sometimes 

### ISSUE THREAD

**Issue by sivathenoobongithub** [25huizengek1/ViTune#364] opened 2024-06-22 13:31 UTC
### Steps to reproduce the bug

1. go to search Bar
2. Searches
3. Gone to Playlist option 
4. Selects Some playlist 
5. Enter into it
6. Sees error

### Expected behavior

![Screenshot_20240622-185827](https://github.com/25huizengek1/ViTune/assets/106529990/3efb63e4-789c-4bbd-bd1d-b2ba7bfe536e)

### Actual behavior

![Screenshot_20240622-185734](https://github.com/25huizengek1/ViTune/assets/106529990/5b859acc-9d68-4d2e-8011-725ad1b06f93)

### ViTune version

Latest version 

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 8.0.1

### Device info

Iam using Samsung Onnxt

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-06-22 21:35
Duplicate of #363

**Closed by 25huizengek1** 2024-06-22 21:35 UTC
Labels: bug
