### ISSUE TITLE
sorting option

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViTune#539] opened 2024-10-31 16:39 UTC
First of all, I would like to thank you for the great app, which gets better with every update.

We now also have the option to sort the songs in the Like Playlist and offline Playlist, which is very nice. It would be nice to have this sorting option in the playlists you have created yourself. Every modern online and offline player has something like this, and I and I think other users would like to see this function.

![Screenshot_2024-10-31-17-31-14-636_app vitune android-edit](https://github.com/user-attachments/assets/0f4e626e-1dba-459a-b115-8aa0fce6e17a)

**Comment by 25huizengek1** [comment] 2024-10-31 22:17
Duplicate of #102

**Closed by 25huizengek1** 2024-10-31 22:17 UTC
Labels: enhancement

**Comment by siggi1984** [comment] 2024-10-31 22:43
> Duplicate of #102

yes okay, but will you add it to the one, because this request has been open for ages
