### ISSUE TITLE
DOWNLOADING 

### ISSUE THREAD

**Issue by muj3eb** [25huizengek1/ViTune#632] opened 2024-12-15 18:45 UTC
## Feature request: ...

Hello mate, i am a user of vi music that is really amazing and mind-blowing one its really impressive thank you for your work mate. So i do really appreciate it if you do something about downloading. Basically when we are about to download any song to listen it offline we are awere which one is downloading so if you add something like loading loop on the downloading song matching with the theme it will really become better and useful 😉 
again thnxxxxx🫡

**Comment by 25huizengek1** [comment] 2024-12-15 20:25
Thank you so much for your appreciation! Duplicate of #531

**Closed by 25huizengek1** 2024-12-15 20:25 UTC
Labels: enhancement
