### ISSUE TITLE
Android TV/Google TV better support

### ISSUE THREAD

**Issue by SQA2009** [25huizengek1/ViTune#614] opened 2024-12-08 16:50 UTC
First, I want to thank you for bringing ViMusic back—it’s an amazing app, and I deeply appreciate the work you’ve put into it. While I understand the primary focus of this app wasn’t TV support, for myself I enjoy using it on a Google TV device. I would like to request improved support for Google TV in your app. Currently, the app's integration in my tv feels limited or inconsistent in areas like navigation, UI scaling, remote control compatibility, and content searching. Enhancing these features would greatly improve my user experience. 

Suggested Improvements:
Optimize the user interface for large-screen displays.
Improve navigation using a tv remote (sometimes work others doesn't) .
Sometimes I click to search to search something and does nothing. I need to go back and search again. 
 
Thank you for considering this request! Please let me know if I need to provide any additional details.

**Comment by 25huizengek1** [comment] 2024-12-08 21:44
Duplicate of #219

**Closed by 25huizengek1** 2024-12-08 21:44 UTC
Labels: enhancement
