### ISSUE TITLE
The returned video ID doesn't match requested one 

### ISSUE THREAD

**Issue by GyuuRanger** [25huizengek1/ViTune#511] opened 2024-10-25 01:57 UTC
### Steps to reproduce the bug

I don't know cuz I open this app and suddenly it crash

### Expected behavior

Maybe my android version 

### Actual behavior

I don't know 

### Screenshots/Screen recordings

![Screenshot_2024-10-25-08-50-29-543_app vitune android](https://github.com/user-attachments/assets/80fce9d3-cf84-43a4-adac-d279b74a7059)

![Screenshot_2024-10-25-08-50-40-152_app vitune android](https://github.com/user-attachments/assets/d157dedc-e4b9-4e1e-ad82-0284a2706d6b)
![Screenshot_2024-10-25-08-50-48-105_app vitune android](https://github.com/user-attachments/assets/85d5742c-b8d7-42e7-8566-11a34616c6cc)

### ViTune version

v1.1.0 RELEASE 

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 6

### Device info

I'm using Xiaomi Redmi 4 Prime

### Upstream reproducibility

I download vimusic and it doesn't work too

### Additional information

I won't able to listening music because that 

Sorry for broken english

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-10-25 01:58
Duplicate of #499

**Closed by 25huizengek1** 2024-10-25 01:58 UTC
Labels: bug
