### ISSUE TITLE
'The returned video ID doesn't match the requested one' bug persists

### ISSUE THREAD

**Issue by scuderiaferrou** [25huizengek1/ViTune#498] opened 2024-10-24 06:02 UTC
### Steps to reproduce the bug

1. Search for non downloaded song
2. Click
3. Unable to listen, the "the returned video ID doesn't match the requested one' message keeps appearing 

### Expected behavior

The music should play and be added to my offline folder

### Actual behavior

The song just doesn't play. The warning keeps appearing on every non downloaded video I tried. I've checked my internet connection and there's no issue with it, it doesn't work on data either. The app is not in deep sleep and battery optimization is off. This happened with the latest versions of vimusic as well as vitune. I tried clearing the cache but all it did was delete all my offline songs and now I can't listen to anything in the app

### Screenshots/Screen recordings

![Screenshot_20241024_024025](https://github.com/user-attachments/assets/72ec694c-ba31-4b45-a45a-84ef4fdb5153)

### ViTune version

v.1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I'm using the Samsung Galaxy s23

### Additional information

I thought this was just a vimusic issue since I know the app was abandoned, but I've tried all three forks I've found that are currently running and none work

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Mexiater** [comment] 2024-10-24 06:09
Duplicate of the other two reported issues.
Unfortunately Piped Api (the service that grabs the song from youtube) is currently down, it has nothing to do with the app itself. We just have to wait.

**Comment by Lasin59** [comment] 2024-10-24 07:48
Vfsfitvnm every vimusic forked apps are down right now. Unplayable

**Comment by Lasin59** [comment] 2024-10-24 07:52
Using spotube rightnow

**Comment by 25huizengek1** [comment] 2024-10-24 14:43
Continuing the conversation in #499

**Closed by 25huizengek1** 2024-10-24 14:43 UTC
Labels: bug
