### ISSUE TITLE
App launching issue 

### ISSUE THREAD

**Issue by JuliyanLoki** [25huizengek1/ViTune#582] opened 2024-11-23 12:03 UTC
### Steps to reproduce the bug

1.open the app after a long time

### Expected behavior

Name of the song's won't appear 

### Actual behavior

Name of the song's won't appear.only the thumbnail will appear 

### Screenshots/Screen recordings

![Screenshot_2024-11-23-17-23-59-40_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/98eeb215-0638-40cf-b8b4-62d932dec303)

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 11

### Device info

I am using realme narzo 20a

### Upstream reproducibility

Not i think 

### Additional information

![Screenshot_2024-11-23-17-23-59-40_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/f0ed3d76-66fb-4a2e-8aa1-f0c267f73315)

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment] 2024-11-23 12:15
Already reported in #469

**Comment by Wqttzicue** [comment] 2024-11-23 12:15
Ingek, please fix it, in next release T-T

**Comment by 25huizengek1** [comment] 2024-12-01 12:20
Duplicate of #469

**Closed by 25huizengek1** 2024-12-01 12:20 UTC
Labels: bug
