### ISSUE TITLE
ideas for the Vitune app

### ISSUE THREAD

**Issue by Skupe17** [25huizengek1/ViTune#535] opened 2024-10-29 16:03 UTC
## Feature request: ...

A clear and concise description of the feature you want to request.

Ideas for the VITUNE App

**1. Playlist Sharing Feature:**
 I would like to implement a playlist sharing feature that allows users to generate a link that points directly to the VITUNE page (This is related and explained further below). This would make it easier for more people to discover the app, allowing users to share their music in a similar way to Spotify only they would not need to download the app itself but would just be taken to a created page of the app with the option to download the app and view the playlist. 

**2. Cross-Platform Compatibility**
: I would like VITUNE to not only work on mobile devices but also on PCs, Macs or TVs. This could increase the visibility and user base of the app, allowing more people to use it in different contexts. As I said before it would be nice if the Vitune app had an official page so that playlist links would not only direct them to the app but so that it could be used in various daily settings, it would be an excellent option. 

**3. White Background Interface:**
 The white background interface is a good choice for the overall aesthetics of the app, providing a clean and modern design. Just like the ViMusic app, it would be nice if they implemented the same aesthetics to make it look better. 

**4. DJ Mode:**
I would like to have a DJ mode that mixes the songs in the playlists smoothly, ensuring smooth transitions between songs of the same genre. In addition, a minimum and maximum number of songs must be set to activate this option. The icon could be a vinyl record to represent this feature. To better understand this feature, it is an option within the playlists so that they are played as if made by a DJ, however, it must be taken into account that this mode should include a timing system so that the songs are connected properly and sudden changes in volume or rhythm are avoided, it is so that they do not only seek to combine the songs of the same genre but can unite the songs in a more fluid way and not only focus on being of the same genre, perhaps through artificial intelligence it would be the best option. 

 **5. Improved AI Recommendation System:**

 I would like to implement an AI system that learns about users' preferences and suggests music based on their tastes. Although there is already a recommendation system, I think it can be improved to offer new songs that are not in the user's playlists, like Spotify does. This would include analyzing listening history and offering a more personalized approach. I would like to see the radio feature in VITUNE offer more new songs, rather than repeating the ones that are already in the playlists. Learning from Spotify's functionality would be crucial, as it is one of the best features of that app.

These are the ideas and improvements I would like to see implemented in VITUNE to boost its functionality and appeal.

**Comment by JondyGems** [comment] 2024-10-29 16:08
i aint reading that foreign language

**Comment by Skupe17** [comment] 2024-10-29 16:20
> i aint reading that foreign language

I just translated it

**Comment by JondyGems** [comment] 2024-10-29 17:58
> > i aint reading that foreign language
> 
> I just translated it

I agree with your suggestions

**Comment by Wqttzicue** [comment] 2024-10-29 20:26
Wont happen in near future.

**Comment by 25huizengek1** [comment] 2024-10-29 21:26
> **1. Playlist Sharing Feature:** I would like to implement a playlist sharing feature that allows users to generate a link that points directly to the VITUNE page (This is related and explained further below). This would make it easier for more people to discover the app, allowing users to share their music in a similar way to Spotify only they would not need to download the app itself but would just be taken to a created page of the app with the option to download the app and view the playlist.

Duplicate of #476

> **2. Cross-Platform Compatibility** : I would like VITUNE to not only work on mobile devices but also on PCs, Macs or TVs. This could increase the visibility and user base of the app, allowing more people to use it in different contexts. As I said before it would be nice if the Vitune app had an official page so that playlist links would not only direct them to the app but so that it could be used in various daily settings, it would be an excellent option.

Duplicate of #190

> **3. White Background Interface:** The white background interface is a good choice for the overall aesthetics of the app, providing a clean and modern design. Just like the ViMusic app, it would be nice if they implemented the same aesthetics to make it look better.

Already exists, go to Settings --> Appearance --> Under colors press Mode --> Light

> **4. DJ Mode:** I would like to have a DJ mode that mixes the songs in the playlists smoothly, ensuring smooth transitions between songs of the same genre. In addition, a minimum and maximum number of songs must be set to activate this option. The icon could be a vinyl record to represent this feature. To better understand this feature, it is an option within the playlists so that they are played as if made by a DJ, however, it must be taken into account that this mode should include a timing system so that the songs are connected properly and sudden changes in volume or rhythm are avoided, it is so that they do not only seek to combine the songs of the same genre but can unite the songs in a more fluid way and not only focus on being of the same genre, perhaps through artificial intelligence it would be the best option.

Duplicate of #294

> **5. Improved AI Recommendation System:**
> 
> I would like to implement an AI system that learns about users' preferences and suggests music based on their tastes. Although there is already a recommendation system, I think it can be improved to offer new songs that are not in the user's playlists, like Spotify does. This would include analyzing listening history and offering a more personalized approach. I would like to see the radio feature in VITUNE offer more new songs, rather than repeating the ones that are already in the playlists. Learning from Spotify's functionality would be crucial, as it is one of the best features of that app.

Won't implement this, as this AI system would be a huge invasion of privacy, which I do not want for users of ViTune.

**Closed by 25huizengek1** 2024-10-29 21:26 UTC
Labels: enhancement

**Comment by Skupe17** [comment] 2024-10-30 00:23
> > **1. Playlist Sharing Feature:** I would like to implement a playlist sharing feature that allows users to generate a link that points directly to the VITUNE page (This is related and explained further below). This would make it easier for more people to discover the app, allowing users to share their music in a similar way to Spotify only they would not need to download the app itself but would just be taken to a created page of the app with the option to download the app and view the playlist.
> 
> Duplicate of #476
> 
> > **2. Cross-Platform Compatibility** : I would like VITUNE to not only work on mobile devices but also on PCs, Macs or TVs. This could increase the visibility and user base of the app, allowing more people to use it in different contexts. As I said before it would be nice if the Vitune app had an official page so that playlist links would not only direct them to the app but so that it could be used in various daily settings, it would be an excellent option.
> 
> Duplicate of #190
> 
> > **3. White Background Interface:** The white background interface is a good choice for the overall aesthetics of the app, providing a clean and modern design. Just like the ViMusic app, it would be nice if they implemented the same aesthetics to make it look better.
> 
> Already exists, go to Settings --> Appearance --> Under colors press Mode --> Light
> 
> > **4. DJ Mode:** I would like to have a DJ mode that mixes the songs in the playlists smoothly, ensuring smooth transitions between songs of the same genre. In addition, a minimum and maximum number of songs must be set to activate this option. The icon could be a vinyl record to represent this feature. To better understand this feature, it is an option within the playlists so that they are played as if made by a DJ, however, it must be taken into account that this mode should include a timing system so that the songs are connected properly and sudden changes in volume or rhythm are avoided, it is so that they do not only seek to combine the songs of the same genre but can unite the songs in a more fluid way and not only focus on being of the same genre, perhaps through artificial intelligence it would be the best option. I really appreciate the clarifications.
> 
> Duplicate of #294
> 
> > **5. Improved AI Recommendation System:**
> > 
> > I would like to implement an AI system that learns about users' preferences and suggests music based on their tastes. Although there is already a recommendation system, I think it can be improved to offer new songs that are not in the user's playlists, like Spotify does. This would include analyzing listening history and offering a more personalized approach. I would like to see the radio feature in VITUNE offer more new songs, rather than repeating the ones that are already in the playlists. Learning from Spotify's functionality would be crucial, as it is one of the best features of that app.
> 
> Won't implement this, as this AI system would be a huge invasion of privacy, which I do not want for users of ViTune.
> 
> 

I am very sorry, if what I proposed was out of bounds and I really started to read everything you cited in your comment about each "proposal" I gave and I am really sorry not to understand the enormous work that it takes to make a slight change and surely it is for many who read the proposals and who know about programming,  They understood that my ideas were lying JDKS , I just want to clarify that I had no idea and that I apologize if any of them are upset or angry.
