### ISSUE TITLE
A spotify-like transition

### ISSUE THREAD

**Issue by Ferjoro20238** [25huizengek1/ViTune#609] opened 2024-12-05 14:44 UTC
As the tilte says try to add a spotify-like transitions to vitune or something close to it with many option like begining transition in the las 10 seconds, 5, 3 etc

(I dont know if tis possible or not since i kow vitune work with youtube music but i would appriciate this new feature to vitune)

**Comment by 25huizengek1** [comment] 2024-12-08 21:49
Duplicate of #294

**Closed by 25huizengek1** 2024-12-08 21:49 UTC
Labels: enhancement
