### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by xxpsychoo** [25huizengek1/ViTune#500] opened 2024-10-24 10:21 UTC
### Steps to reproduce the bug

Clik

### Expected behavior

Bug

### Actual behavior

Always appears writing "The returned video ID doesn't match the requested one"
This happened after I updated to the latest version.. I know there is an auto skip feature if there is a problem.. but this always appears do I have to skip all the songs in this application? Thank you

### Screenshots/Screen recordings

![Screenshot_2024-10-24-17-15-29-65_c41d99f29ddb98f2b2d1f5dfe2e7da20](https://github.com/user-attachments/assets/a4bfb274-6116-4e26-a726-8f7b259ed162)

### ViTune version

v.1.10

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

14

### Device info

I am using realme gt master

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by MLGHerobrine** [comment] 2024-10-24 14:39
Piped is down, we just have to wait. Duplicate of #477

**Comment by 25huizengek1** [comment] 2024-10-24 14:42
Piped is definitely not down (and it shouldn't even matter, we only use Piped as a back-up for when YouTube blocks requests), but experiencing the same issue as I described in #499

![Screenshot_20241024-164048.png](https://github.com/user-attachments/assets/571dd76d-d1a6-40ad-8e67-cc09ce336278)

**Closed** 2024-10-24 14:42 UTC
Labels: bug
