### ISSUE TITLE
Weird App Behavior 

### ISSUE THREAD

**Issue by L9my** [25huizengek1/ViTune#506] opened 2024-10-24 19:39 UTC
## Weird App Behavior

When i'm trying to play some song's i'm getting a "The returned video ID doesn't match the requested one" error![Screenshot_2024-10-24-21-39-15-98_c41d99f29ddb98f2b2d1f5dfe2e7da20.jpg](https://github.com/user-attachments/assets/954b8d9e-5da8-42e1-97da-812f3d3c67a3)

**Comment by L9my** [comment] 2024-10-24 19:40
same thing happends on my other phone, both are running android 14

**Comment by 25huizengek1** [comment] 2024-10-24 23:35
Duplicate of #499

**Closed by 25huizengek1** 2024-10-24 23:35 UTC
Labels: enhancement
