### ISSUE TITLE
can't play music 

### ISSUE THREAD

**Issue by ash1ai** [25huizengek1/ViTune#656] opened 2024-12-22 11:55 UTC
### Steps to reproduce the bug

it happen in every music i tried to play

### Expected behavior

the song should be play normally 

### Actual behavior

the song doesn't even play showing an error "An unknown playback error has occurred"

### Screenshots/Screen recordings

![Screenshot_2024-12-22-18-51-52-400_app vitune android](https://github.com/user-attachments/assets/1ebc9ba4-71d5-4cdf-892f-b8b6c0283640)

### Logs

--------- beginning of system
[2024-12-22T18:46:03.810Z] Debug (15297) MiuiDownscaleImpl - set override inverted scale : 1.0
[2024-12-22T18:46:03.824Z] Info (15297) ActivityThread - SetSystemFontMap done
[2024-12-22T18:46:03.906Z] Info (15297) ActivityThread - TrafficStats init done
[2024-12-22T18:46:03.918Z] Info (15297) ActivityThread - Miui Feature Init done
[2024-12-22T18:46:04.003Z] Debug (15297) FramePredict - FramePredict init: false
[2024-12-22T18:46:04.013Z] Info (15297) ActivityThread - HardwareRenderer preload  done
[2024-12-22T18:46:04.095Z] Debug (15297) FramePredict - init success
[2024-12-22T18:46:04.098Z] Error (15297) FramePredict - registerContentObserver fail
[2024-12-22T18:46:04.244Z] Debug (15297) UserSceneDetector - invoke error.
[2024-12-22T18:46:04.487Z] Debug (15297) UserSceneDetector - invoke error.
[2024-12-22T18:46:04.600Z] Warning (15297) Looper   - PerfMonitor doFrame : time=355ms vsyncFrame=8610059 latency=137ms procState=-1 historyMsgCount=9 (msgIndex=1 wall=102ms seq=6 late=21ms h=android.app.ActivityThread$H w=159) (msgIndex=5 wall=118ms seq=10 late=41ms h=android.app.ActivityThread$H w=114)
[2024-12-22T18:46:04.713Z] Debug (15297) UserSceneDetector - invoke error.
[2024-12-22T18:46:04.779Z] Warning (15297) Looper   - PerfMonitor doFrame : time=66ms vsyncFrame=8610074 latency=463ms procState=-1 historyMsgCount=25 (msgIndex=1 wall=355ms seq=15 late=137ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
[2024-12-22T18:46:05.138Z] Debug (15297) UserSceneDetector - invoke error.
[2024-12-22T18:46:05.147Z] Warning (15297) Looper   - PerfMonitor doFrame : time=10ms vsyncFrame=8610127 latency=420ms procState=-1 historyMsgCount=26 (msgIndex=1 wall=66ms seq=40 late=463ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=10 wall=174ms seq=49 late=181ms h=android.os.Handler c=A3.j) (msgIndex=21 wall=102ms seq=60 late=334ms h=android.os.Handler c=A3.D)
[2024-12-22T18:46:05.707Z] Debug (15297) UserSceneDetector - invoke error.
[2024-12-22T18:46:05.759Z] Warning (15297) Looper   - PerfMonitor doFrame : time=53ms vsyncFrame=8610186 latency=463ms procState=-1 historyMsgCount=7 (msgIndex=1 wall=248ms seq=77 late=91ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver) (msgIndex=2 wall=74ms seq=78 late=332ms h=android.os.Handler c=A3.i) (msgIndex=5 wall=80ms seq=81 late=385ms h=android.os.Handler c=A3.D)
[2024-12-22T18:46:11.770Z] Debug (15297) MiuiMultiWindowUtils - freeform resolution args raw data:{  "wide_default":{    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.168,"left_margin":0.484},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.1222,"left_margin":0.59745},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.2596,"left_margin":0.2624},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.213,"left_margin":0.3758}    },    "mini_freeform_args":{        "vertical_portrait":{"original_ratio":0.147},        "horizontal_portrait":{"original_ratio":0.147},        "vertical_landscape":{"original_ratio":0.165},        "horizontal_landscape":{"original_ratio":0.165}    }  },  "narrow_default": {    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.74,"top_margin":0.0753,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.5756,"top_margin":-1,"left_margin":0.0753},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":0.0753,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":-1,"left_margin":0.0753}    },    "mini_freeform_args":{        "vertical_portrait":{"original_ratio":0.26},        "horizontal_portrait":{"original_ratio":0.26},        "vertical_landscape":{"original_ratio":0.293},        "horizontal_landscape":{"original_ratio":0.293}    }  },  "regular_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":1,"original_scale":0.7,"top_margin":0.109,"left_margin":-1},      "horizontal_portrait":{"aspect_ratio":0.6667, "original_ratio":1,"original_scale":0.6102,"top_margin":-1,"left_margin":0.026},      "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.4244,"top_margin":0.109,"left_margin":-1},      "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.4244,"top_margin":-1,"left_margin":0.026}    },    "mini_freeform_args":{      "vertical_portrait":{"original_ratio":0.25},      "horizontal_portrait":{"original_ratio":0.25},      "vertical_landscape":{"original_ratio":0.25},      "horizontal_landscape":{"original_ratio":0.25}    }  },  "pad_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.375,"original_scale":0.835,"top_margin":0.049,"left_margin":0.2775},      "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.375,"original_scale":0.835,"top_margin":-1,"left_margin":0.6525},      "vertical_landscape":{"aspect_ratio":-1, "original_ratio":1,"original_scale":0.468,"top_margin":0.049,"left_margin":-1},      "horizontal_landscape":{"aspect_ratio":-1, "original_ratio":1,"original_scale":0.468,"top_margin":-1,"left_margin":0.4976}    },    "mini_freeform_args":{      "vertical_portrait":{"original_ratio":0.144},      "horizontal_portrait":{"original_ratio":0.144},      "vertical_landscape":{"original_ratio":0.2},      "horizontal_landscape":{"original_ratio":0.2}    }  }}
[2024-12-22T18:46:11.771Z] Debug (15297) MiuiMultiWindowUtils - initFreeFormResolutionArgs failed, device is sapphire
[2024-12-22T18:46:12.361Z] Debug (15297) ActivityThread - Fail to check app heapsize due to java.lang.NoSuchMethodException: dalvik.system.VMRuntime.getBlockingGcCountForAlloc []
--------- beginning of main
[2024-12-22T18:51:48.876Z] Debug (15297) AppScoutStateMachine - 15297-ScoutStateMachinecreated
[2024-12-22T18:51:48.877Z] Debug (15297) ActivityThread - handleBoundsCompatInfoChanged remove: name=app.vitune.android
[2024-12-22T18:51:48.925Z] Debug (15297) SecurityManager - checkAccessControl flag0
[2024-12-22T18:51:48.953Z] Warning (15297) libc     - Access denied finding property "vendor.display.enable_optimal_refresh_rate"
[2024-12-22T18:51:48.953Z] Warning (15297) libc     - Access denied finding property "vendor.gpp.create_frc_extension"
[2024-12-22T18:51:48.948Z] Warning (15297) .vitune.android - type=1400 audit(0.0:260483): avc:  denied  { read } for  name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=457 scontext=u:r:untrusted_app:s0:c172,c257,c512,c768 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0 app=app.vitune.android
[2024-12-22T18:51:48.955Z] Debug (15297) VRI[MainActivity] - vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4932 android.view.ViewRootImpl.doTraversal:3543 android.view.ViewRootImpl$TraversalRunnable.run:11550 android.view.Choreographer$CallbackRecord.run:1747 android.view.Choreographer$CallbackRecord.run:1756 
[2024-12-22T18:51:48.956Z] Debug (15297) VRI[MainActivity] - vri.Setup new sync=wmsSync-VRI[MainActivity]#2
[2024-12-22T18:51:49.056Z] Debug (15297) VRI[MainActivity] - vri.reportDrawFinished
[2024-12-22T18:51:49.205Z] Info (15297) HandWritingStubImpl - refreshLastKeyboardType: 1
[2024-12-22T18:51:49.205Z] Info (15297) HandWritingStubImpl - getCurrentKeyboardType: 1
[2024-12-22T18:51:49.417Z] Warning (15297) RenderInspector - QueueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=14, avg=10 ms, max=12 ms.
[2024-12-22T18:51:51.006Z] Warning (15297) RenderInspector - QueueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=25, avg=7 ms, max=13 ms.
[2024-12-22T18:51:51.524Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175089286, downTime=175089286, phoneEventTime=18:51:51.520 } moveCount:0
[2024-12-22T18:51:51.525Z] Warning (15297) .vitune.android - Missing inline cache for void android.view.InputEventManagerImpl.logOnInputEvent(android.view.InputEvent, java.lang.String)
[2024-12-22T18:51:51.541Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_CANCEL, id[0]=0, id[1]=1, id[2]=2, pointerCount=3, eventTime=175089305, downTime=175089286, phoneEventTime=18:51:51.539 } moveCount:0
[2024-12-22T18:51:52.950Z] Error (15297) LongScreenshotUtils - inLargeScreen false
[2024-12-22T18:51:52.950Z] Info (15297) LongScreenshotUtils -  focus:true
[2024-12-22T18:51:52.955Z] Info (15297) LongScreenshotUtils - current ratio width:1.0, height:1.0
[2024-12-22T18:51:53.278Z] Warning (15297) RenderInspector - QueueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=1, avg=11 ms, max=11 ms.
[2024-12-22T18:51:54.468Z] Debug (15297) UserSceneDetector - invoke error.
[2024-12-22T18:51:54.613Z] Warning (15297) RenderInspector - QueueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=5, avg=10 ms, max=39 ms.
[2024-12-22T18:51:54.755Z] Warning (15297) RenderInspector - QueueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=1, avg=27 ms, max=27 ms.
[2024-12-22T18:51:55.135Z] Error (15297) FenceTime - FenceTime::applyTrustedSnapshot: signalTime mismatch. (175092845834924 (old) != -1 (new))
[2024-12-22T18:51:55.203Z] Error (15297) FenceTime - FenceTime::applyTrustedSnapshot: signalTime mismatch. (175092845834924 (old) != -1 (new))
[2024-12-22T18:51:55.204Z] Warning (15297) RenderInspector - QueueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=8, avg=7 ms, max=15 ms.
[2024-12-22T18:51:55.215Z] Warning (15297) WindowOnBackDispatcher - sendCancelIfRunning: isInProgress=false callback=c.x@b92a6de
[2024-12-22T18:51:55.272Z] Debug (15297) ActivityThread - Fail to check app heapsize due to java.lang.NoSuchMethodException: dalvik.system.VMRuntime.getBlockingGcCountForAlloc []
[2024-12-22T18:53:10.722Z] Debug (15297) AppScoutStateMachine - 15297-ScoutStateMachinecreated
[2024-12-22T18:53:10.723Z] Debug (15297) ActivityThread - handleBoundsCompatInfoChanged remove: name=app.vitune.android
[2024-12-22T18:53:10.773Z] Debug (15297) SecurityManager - checkAccessControl flag0
[2024-12-22T18:53:10.777Z] Debug (15297) VRI[MainActivity] - vri.reportNextDraw android.view.ViewRootImpl.handleResized:2756 android.view.ViewRootImpl.-$$Nest$mhandleResized:0 android.view.ViewRootImpl$W.resized:12708 android.app.servertransaction.WindowStateResizeItem.execute:64 android.app.servertransaction.WindowStateTransactionItem.execute:59 
[2024-12-22T18:53:10.795Z] Warning (15297) libc     - Access denied finding property "vendor.display.enable_optimal_refresh_rate"
[2024-12-22T18:53:10.795Z] Warning (15297) libc     - Access denied finding property "vendor.gpp.create_frc_extension"
[2024-12-22T18:53:10.792Z] Warning (15297) .vitune.android - type=1400 audit(0.0:260602): avc:  denied  { read } for  name="u:object_r:vendor_display_prop:s0" dev="tmpfs" ino=457 scontext=u:r:untrusted_app:s0:c172,c257,c512,c768 tcontext=u:object_r:vendor_display_prop:s0 tclass=file permissive=0 app=app.vitune.android
[2024-12-22T18:53:10.796Z] Debug (15297) VRI[MainActivity] - vri.reportNextDraw android.view.ViewRootImpl.performTraversals:4932 android.view.ViewRootImpl.doTraversal:3543 android.view.ViewRootImpl$TraversalRunnable.run:11550 android.view.Choreographer$CallbackRecord.run:1747 android.view.Choreographer$CallbackRecord.run:1756 
[2024-12-22T18:53:10.796Z] Debug (15297) VRI[MainActivity] - vri.Setup new sync=wmsSync-VRI[MainActivity]#4
[2024-12-22T18:53:10.857Z] Debug (15297) VRI[MainActivity] - vri.reportDrawFinished
[2024-12-22T18:53:10.871Z] Error (15297) FrameEvents - addRelease: Did not find frame.
[2024-12-22T18:53:10.882Z] Error (15297) FrameEvents - addRelease: Did not find frame.
[2024-12-22T18:53:10.907Z] Error (15297) FrameEvents - addRelease: Did not find frame.
[2024-12-22T18:53:10.916Z] Error (15297) FrameEvents - addRelease: Did not find frame.
[2024-12-22T18:53:10.941Z] Warning (15297) RenderInspector - DequeueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=2, avg=10 ms, max=11 ms.
[2024-12-22T18:53:10.942Z] Info (15297) HandWritingStubImpl - refreshLastKeyboardType: 1
[2024-12-22T18:53:10.942Z] Info (15297) HandWritingStubImpl - getCurrentKeyboardType: 1
[2024-12-22T18:53:11.215Z] Warning (15297) RenderInspector - QueueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=17, avg=10 ms, max=11 ms.
[2024-12-22T18:53:11.549Z] Warning (15297) RenderInspector - QueueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=4, avg=7 ms, max=9 ms.
[2024-12-22T18:53:11.583Z] Warning (15297) WindowOnBackDispatcher - sendCancelIfRunning: isInProgress=false callback=c.x@b92a6de
[2024-12-22T18:53:12.420Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175170182, downTime=175170182, phoneEventTime=18:53:12.416 } moveCount:0
[2024-12-22T18:53:12.483Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175170247, downTime=175170182, phoneEventTime=18:53:12.482 } moveCount:0
[2024-12-22T18:53:13.792Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175171556, downTime=175171556, phoneEventTime=18:53:13.791 } moveCount:0
[2024-12-22T18:53:13.854Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175171618, downTime=175171556, phoneEventTime=18:53:13.853 } moveCount:3
[2024-12-22T18:53:14.374Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175172137, downTime=175172137, phoneEventTime=18:53:14.371 } moveCount:0
[2024-12-22T18:53:14.607Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175172370, downTime=175172137, phoneEventTime=18:53:14.604 } moveCount:23
[2024-12-22T18:53:20.032Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175177792, downTime=175177792, phoneEventTime=18:53:20.026 } moveCount:0
[2024-12-22T18:53:20.133Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175177896, downTime=175177792, phoneEventTime=18:53:20.130 } moveCount:2
[2024-12-22T18:53:21.074Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175178837, downTime=175178837, phoneEventTime=18:53:21.071 } moveCount:0
[2024-12-22T18:53:21.177Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175178940, downTime=175178837, phoneEventTime=18:53:21.174 } moveCount:9
[2024-12-22T18:53:22.531Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175180293, downTime=175180293, phoneEventTime=18:53:22.527 } moveCount:0
[2024-12-22T18:53:22.577Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175180341, downTime=175180293, phoneEventTime=18:53:22.575 } moveCount:1
[2024-12-22T18:53:23.122Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175180883, downTime=175180883, phoneEventTime=18:53:23.118 } moveCount:0
[2024-12-22T18:53:23.230Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175180994, downTime=175180883, phoneEventTime=18:53:23.228 } moveCount:11
[2024-12-22T18:53:26.909Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175184671, downTime=175184671, phoneEventTime=18:53:26.905 } moveCount:0
[2024-12-22T18:53:27.001Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175184765, downTime=175184671, phoneEventTime=18:53:27.000 } moveCount:2
[2024-12-22T18:53:28.907Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175186671, downTime=175186671, phoneEventTime=18:53:28.905 } moveCount:0
[2024-12-22T18:53:28.985Z] Info (15297) MiInputConsumer - optimized resample latency: 997509 ns
[2024-12-22T18:53:29.030Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175186794, downTime=175186671, phoneEventTime=18:53:29.028 } moveCount:14
[2024-12-22T18:53:29.653Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175187416, downTime=175187416, phoneEventTime=18:53:29.650 } moveCount:0
[2024-12-22T18:53:29.718Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175187476, downTime=175187416, phoneEventTime=18:53:29.711 } moveCount:7
[2024-12-22T18:53:30.398Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175188162, downTime=175188162, phoneEventTime=18:53:30.397 } moveCount:0
[2024-12-22T18:53:32.208Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175189972, downTime=175188162, phoneEventTime=18:53:32.206 } moveCount:185
[2024-12-22T18:53:33.157Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175190918, downTime=175190918, phoneEventTime=18:53:33.153 } moveCount:0
[2024-12-22T18:53:33.201Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175190961, downTime=175190918, phoneEventTime=18:53:33.196 } moveCount:5
[2024-12-22T18:53:33.646Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175191410, downTime=175191410, phoneEventTime=18:53:33.644 } moveCount:0
[2024-12-22T18:53:33.698Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175191462, downTime=175191410, phoneEventTime=18:53:33.696 } moveCount:7
[2024-12-22T18:53:47.834Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175205593, downTime=175205593, phoneEventTime=18:53:47.827 } moveCount:0
[2024-12-22T18:53:47.925Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175205688, downTime=175205593, phoneEventTime=18:53:47.922 } moveCount:10
[2024-12-22T18:53:48.183Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175205944, downTime=175205944, phoneEventTime=18:53:48.178 } moveCount:0
[2024-12-22T18:53:48.276Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175206036, downTime=175205944, phoneEventTime=18:53:48.270 } moveCount:8
[2024-12-22T18:53:48.687Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175206446, downTime=175206446, phoneEventTime=18:53:48.680 } moveCount:0
[2024-12-22T18:53:48.762Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175206526, downTime=175206446, phoneEventTime=18:53:48.761 } moveCount:9
[2024-12-22T18:53:49.461Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175207221, downTime=175207221, phoneEventTime=18:53:49.455 } moveCount:0
[2024-12-22T18:53:49.501Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175207264, downTime=175207221, phoneEventTime=18:53:49.498 } moveCount:4
[2024-12-22T18:53:50.300Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175208062, downTime=175208062, phoneEventTime=18:53:50.296 } moveCount:0
[2024-12-22T18:53:50.380Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175208143, downTime=175208062, phoneEventTime=18:53:50.377 } moveCount:0
[2024-12-22T18:53:51.246Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175209010, downTime=175209010, phoneEventTime=18:53:51.245 } moveCount:0
[2024-12-22T18:53:51.311Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175209075, downTime=175209010, phoneEventTime=18:53:51.310 } moveCount:1
[2024-12-22T18:53:52.330Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175210091, downTime=175210091, phoneEventTime=18:53:52.326 } moveCount:0
[2024-12-22T18:53:52.403Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175210166, downTime=175210091, phoneEventTime=18:53:52.400 } moveCount:9
[2024-12-22T18:53:52.838Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175210602, downTime=175210602, phoneEventTime=18:53:52.836 } moveCount:0
[2024-12-22T18:53:52.881Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175210643, downTime=175210602, phoneEventTime=18:53:52.877 } moveCount:5
[2024-12-22T18:53:53.682Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175211445, downTime=175211445, phoneEventTime=18:53:53.679 } moveCount:0
[2024-12-22T18:53:53.755Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175211517, downTime=175211445, phoneEventTime=18:53:53.751 } moveCount:0
[2024-12-22T18:53:54.286Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175212049, downTime=175212049, phoneEventTime=18:53:54.283 } moveCount:0
[2024-12-22T18:53:54.295Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175212052, downTime=175212049, phoneEventTime=18:53:54.286 } moveCount:0
[2024-12-22T18:53:54.732Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175212496, downTime=175212496, phoneEventTime=18:53:54.730 } moveCount:0
[2024-12-22T18:53:54.786Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175212548, downTime=175212496, phoneEventTime=18:53:54.783 } moveCount:0
[2024-12-22T18:53:56.462Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175214224, downTime=175214224, phoneEventTime=18:53:56.458 } moveCount:0
[2024-12-22T18:53:56.532Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=175214296, downTime=175214224, phoneEventTime=18:53:56.531 } moveCount:5
[2024-12-22T18:53:56.624Z] Warning (15297) RenderInspector - QueueBuffer time out on app.vitune.android/app.vitune.android.MainActivity, count=1, avg=9 ms, max=9 ms.
[2024-12-22T18:53:57.075Z] Info (15297) MIUIInput - [MotionEvent] ViewRootImpl windowName 'app.vitune.android/app.vitune.android.MainActivity', { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=175214838, downTime=175214838, phoneEventTime=18:53:57.072 } moveCount:0

### ViTune version

v1.1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

android 15

### Device info

redmi note 13 4g

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-12-23 20:00
Duplicate of #555

**Closed** 2024-12-23 20:00 UTC
Labels: bug
