### ISSUE TITLE
Way to remove tabs from the nav bar, although I love the selection I'm a student and try to aim for minimum distractions and would prefer to be able to remove the quick picks and discover tab

### ISSUE THREAD

**Issue by Geigerbuzz** [25huizengek1/ViTune#416] opened 2024-08-31 02:10 UTC
## Feature request: ...

A clear and concise description of the feature you want to request.

**Comment by 25huizengek1** [comment] 2024-09-01 20:26
Duplicate of #350

**Closed by 25huizengek1** 2024-09-01 20:26 UTC
Labels: enhancement
