### ISSUE TITLE
Functionality for adding cover art to playlists 

### ISSUE THREAD

**Issue by CardMasterLive** [25huizengek1/ViTune#235] opened 2024-04-13 14:48 UTC
Title kinda says it all, Will elaborate if needed

**Comment by Syntax-Err5** [comment] 2024-04-13 23:03
Duplicate of #207
Adding your own cover images would massively increase the size of the database.

**Comment by 25huizengek1** [comment] 2024-04-14 15:37
Duplicate of #207

**Closed by 25huizengek1** 2024-04-14 15:37 UTC
Labels: enhancement
