### ISSUE TITLE
The song title becomes invisible when changing its position in the queue 

### ISSUE THREAD

**Issue by FaqatZubair1** [25huizengek1/ViTune#184] opened 2024-03-24 08:28 UTC
### Steps to reproduce the bug

Try to move a song up or down in a queue

### Expected behavior

The song should remain visible while moving it

### Actual behavior

It becomes invisible as we move it fast

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViTune/assets/161596117/7e1075e6-78ba-49c0-b4a6-b85c61c6daab

### ViTune version

1.0.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

Motorola moto g34

### Upstream reproducibility

No this issue can't be reproduced with vimusic 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Enigma1309** [comment] 2024-03-24 12:36
It's a bug, the song pallet gets moved up from the actual finger-position when we move it near the either of the edges of screen,
You can see that it's actually moved up a little by dragging your finger to the bottom

**Comment by 25huizengek1** [comment] 2024-03-24 17:06
Thank you for your report. Duplicate of #127, it is intentional (overscroll behavior) but I guess I should clip it. Moving the conversation to #127 nonetheless...

**Closed by 25huizengek1** 2024-03-24 17:06 UTC
Labels: bug
