### ISSUE TITLE
Suggestions for improving the Quick Picks tab

### ISSUE THREAD

**Issue by yonoff** [25huizengek1/ViTune#332] opened 2024-06-03 11:45 UTC
Sometimes the "Quick picks" tab is empty and the message "an error has occurred" appears.
The problem appears to be related to network connection issues.
Switching to the "Discover" tab and then back to the "Quick picks" tab solves the problem.
It would be great to be able to refresh the "Quick picks" tab manually:
please add  to the “Quick picks” tab a refresh button or a pull down to refresh gesture.
![photo1717414969](https://github.com/25huizengek1/ViTune/assets/9549832/d14478fc-7359-43cb-b15e-3c12c0ecc894)

**Comment by Enigma1309** [comment] 2024-06-04 07:41
dupe of #199 

as an alternative you can enable  caching of  the quick-pics in settings

**Comment by yonoff** [comment] 2024-06-04 08:31
> dupe of #199
> 
> as an alternative you can enable caching of the quick-pics in settings

Caching is already enabled, but it does not help:

![photo1717488956](https://github.com/25huizengek1/ViTune/assets/9549832/e1939724-5f8e-4291-9777-e8726ea8a2cf)

**Comment by yonoff** [comment] 2024-06-04 08:57
Also, I found another fork of ViMusic on github: [**Music You**](https://github.com/DanielSevillano/music-you)

In addition to the **Last played** option for the Quick Picks source there is a **Most played** option, it would be great to have this selection in the ViTune app as well:

![photo1717488956](https://github.com/25huizengek1/ViTune/assets/9549832/92be7d77-835d-467a-b447-4220c4919406)

**Comment by 25huizengek1** [comment] 2024-06-04 14:02
@yonoff This is already the case: Settings ==> Appearance

Duplicate of #199

**Closed by 25huizengek1** 2024-06-04 14:02 UTC
Labels: enhancement

**Comment by Monoxide8969** [comment] 2024-06-04 14:45
ViTune only has "Trending" and "Last played" as sources for quick pics. Having also a "Most played" option would be nice.
