### ISSUE TITLE
No songs playing 

### ISSUE THREAD

**Issue by devika15** [25huizengek1/ViTune#508] opened 2024-10-24 20:39 UTC
### Steps to reproduce the bug

Click on song 

### Expected behavior

Play song 

### Actual behavior

Says returned ID doesn't match

### ViTune version

1.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

14

### Device info

Samsung stock Android 14

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by YeetusFeetus420** [comment] 2024-10-24 21:10
Yeah same thing here, I'm in Egypt which is a supported country, this also happened with me on vimusic yesterday which is why I'm switching to this but the problem is also happening with this app
![Screenshot_20241025-000929](https://github.com/user-attachments/assets/80050d53-e43e-4361-83e1-86933482c5f9)

**Comment by Jarletoss** [comment] 2024-10-24 22:05
This also happened to me too! It happened with vimusic first a few days ago and I thought my save file corrupted so I swotched to a few forks of vimusic and none of them worked because of the same issue. YouTube changed its API in some way and ruined just about every fork of vimusic
![Screenshot_20241025_000508_it vfsfitvnm vimusic](https://github.com/user-attachments/assets/ebcb44b6-bab8-421d-bf8e-681da0d28d26)

**Comment by Wqttzicue** [comment] 2024-10-24 23:27
Duplicate of #499

**Comment by 25huizengek1** [comment] 2024-10-24 23:35
Duplicate of #499

**Closed by 25huizengek1** 2024-10-24 23:35 UTC
Labels: bug
