### ISSUE TITLE
Lyrics Translation

### ISSUE THREAD

**Issue by haernerdy** [25huizengek1/ViTune#296] opened 2024-05-18 23:29 UTC
Please, can you implement a button to be able to translate non-English lyrics? It would be really helpful. Thanks!
![Screenshot_20240519_001911.jpg](https://github.com/25huizengek1/ViTune/assets/111110471/4eb1de30-6d4d-4444-8312-02643ffd8cd1)

**Comment by 25huizengek1** [comment] 2024-05-19 02:40
Duplicate of #208

**Closed by 25huizengek1** 2024-05-19 02:40 UTC
Labels: enhancement
