### ISSUE TITLE
Queue not working as it should

### ISSUE THREAD

**Issue by brnwlshubh** [25huizengek1/ViTune#227] opened 2024-04-11 17:44 UTC
### Steps to reproduce the bug

Play any song 
Then Start Radio from that song.

### Expected behavior

It should be align as queue not overlap each other.

### Actual behavior

Current playing song is overlapping over the upcoming songs.

### Screenshots/Screen recordings

![SmartSelect_20240411_230845](https://github.com/25huizengek1/ViTune/assets/77489594/95994267-0292-43ed-b99c-41a4c54b9dcb)

### ViTune version

v1.0.0

### What kind of build are you using?

Nightly (F-Droid)

### Android version

Android 14

### Device info

I'm using Samsung F34

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by brnwlshubh** [comment] 2024-04-11 18:31
https://github.com/25huizengek1/ViTune/assets/77489594/a5ca2b32-5864-49b7-92bf-36d2b2498b61

Here is the recording of the actual scene.

**Comment by 25huizengek1** [comment] 2024-04-11 18:52
Can't reproduce. Will investigate later.

**Comment by 25huizengek1** [comment] 2024-04-11 23:38
Duplicate of #127.

**Closed by 25huizengek1** 2024-04-11 23:38 UTC
Labels: bug, duplicate, can't reproduce, prio:normal
