### ISSUE TITLE
Requesting a Feature for ViTune

### ISSUE THREAD

**Issue by Aqua-X7** [25huizengek1/ViTune#592] opened 2024-11-27 02:05 UTC
## Feature request: 

Allow us to customise our own playlist like: Changing their thumbnail (from our own custom image), descriptions for that Playlist, etc.

**Comment by Wqttzicue** [comment] 2024-11-27 11:59
Already suggested

**Comment by Wqttzicue** [comment] 2024-11-27 12:00
Btw @25huizengek1 please add Desync button to plsylists, cuz i saved sone playlist from ytm and i removed and added some songs, but after some time it just synced back to original, so annoying.

Or desync playlist if you edited it somehow.

**Comment by 25huizengek1** [comment] 2024-12-01 12:12
Duplicate of #533

**Closed by 25huizengek1** 2024-12-01 12:12 UTC
Labels: enhancement
