### ISSUE TITLE
Add login to YouTube music and sync playlist 
Add import playlist
Add 

### ISSUE THREAD

**Issue by abdalftah193** [25huizengek1/ViTune#565] opened 2024-11-14 11:58 UTC
## Feature request: ...

A clear and concise description of the feature you want to request.

**Comment by Wqttzicue** [comment] 2024-11-14 15:23
Already suggested, this **WON'T** happen.

**Comment by abdalftah193** [comment] 2024-11-14 16:03
Why?

**Comment by Wqttzicue** [comment] 2024-11-14 16:29
> Why? 

ViTune is more privacy orientated player, and integrationf of googöe services will completely ruin it and also this will mean ads in music.

ViTune uses Piped Api instead of Youtube.

**Comment by abdalftah193** [comment] 2024-11-14 17:15
Also you can add features from the ri Music application such as adding a playlist from YouTube through a link

**Comment by Wqttzicue** [comment] 2024-11-15 06:50
> Also you can add features from the ri Music application such as adding a playlist from YouTube through a link

Such thing is already suggested, and its accepted someway

**Comment by 25huizengek1** [comment] 2024-11-20 20:55
Duplicate of #199

**Closed by 25huizengek1** 2024-11-20 20:55 UTC
Labels: enhancement
