### ISSUE TITLE
unable to play a song

### ISSUE THREAD

**Issue by fanaH7** [25huizengek1/ViTune#510] opened 2024-10-25 00:30 UTC
### Steps to reproduce the bug

1. open the app
2. click on any song
3. it's shown that "the returned video ID doesn't match the requested one"

### Expected behavior

when click on the song, it should be playing 

### Actual behavior

instead, it's shown that "the returned video ID doesn't match the requested one" and can't be playing 

### Screenshots/Screen recordings

![Screenshot_20241025-082242](https://github.com/user-attachments/assets/c79b1f9a-055b-49d2-88ff-3cf27c7fdef1)

### ViTune version

v.1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

l am using Infinix Note 40 Pro, running stock Android 14

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by MLGHerobrine** [comment] 2024-10-25 01:33
This is a known issue. Piped API is down, please wait.

**Comment by 25huizengek1** [comment] 2024-10-25 02:00
@MLGHerobrine The Piped instance ViTune uses is not down, it just experiences the exact same issues as ViTune.

**Comment by 25huizengek1** [comment] 2024-10-25 02:00
That said, duplicate of #499

**Closed by 25huizengek1** 2024-10-25 02:00 UTC
Labels: bug
