### ISSUE TITLE
ViTunes/ViMusic error "The returned video id doesn't match the requested one"

### ISSUE THREAD

**Issue by P4r73x3** [25huizengek1/ViTune#515] opened 2024-10-25 09:51 UTC
### Steps to reproduce the bug

1. Open ViTunes/ViMusic
2. Select any song
3. Instead of the music, a notification on the banner appears as "The returned video ID doesn't match the requested one"

### Expected behavior

Instead, the music shall start playing, as we tap on it

### Actual behavior

Previously, the ViMusic apk tht I've been using, was fairly doing better, though the notification of "**the returned....one**" used to appear,  **it'd go away after tapping the banner once or twice**, but recently, _**even after multiple taps, the notification comes again, and completely prevents the music from starting**_ 

### Screenshots/Screen recordings

![Screenshot_20241025_151020](https://github.com/user-attachments/assets/75f08249-2655-48fb-bcd0-3b805f6b3f9b)

### ViTune version

v1.1.10

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 13

### Device info

I am using Samsung A14, using OneUi

### Upstream reproducibility

Yeah this issue is similar to the one faced on ViMusic

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment] 2024-10-25 10:03
Duplicate of #499

**Comment by P4r73x3** [comment] 2024-10-25 10:14
> Duplicate of #499

So uhm, what's the solution?

**Comment by H3T-Shah** [comment] 2024-10-25 10:25
> > Duplicate of #499
> 
> So uhm, what's the solution?

Read the #499 thread. He is already working on it. Mentioning the same issue again and again will not help.

**Comment by P4r73x3** [comment] 2024-10-25 10:27
> > > Duplicate of #499
> > 
> > So uhm, what's the solution?
> 
> Read the #499 thread. He is already working on it. Mentioning the same issue again and again will not help.

I see, my apologies.

**Closed** 2024-10-25 10:28 UTC
Labels: bug

**Comment by Prabaljain207** [comment] 2024-10-25 12:09
![Uploading Screenshot_2024-10-25-17-15-52-322_it.vfsfitvnm.vimusic.jpg…]()
