### ISSUE TITLE
"Other Versions" does not function at all

### ISSUE THREAD

**Issue by JMPesce** [25huizengek1/ViTune#352] opened 2024-06-12 19:26 UTC
### Steps to reproduce the bug

1. Go to any album that has an alternate version
![Screenshot_20240612-151509](https://github.com/25huizengek1/ViTune/assets/6206297/26bf5dcb-6d9a-41bd-8133-2cd691f45e1f)

2. Click "Other Version", and the item flashes and shows nothing.
![Screenshot_20240612-151514](https://github.com/25huizengek1/ViTune/assets/6206297/2346b0d1-3201-45b8-b687-7252edb24805)

3. Showing the above album does actually have an "Other Version"
![Screenshot_20240612-151550](https://github.com/25huizengek1/ViTune/assets/6206297/859cb9b1-4d52-4005-9a63-f02116bf97f8)

### Expected behavior

The deluxe of the album should show up in Other Versions. 

### Actual behavior

The alternate version does not show up, and furthermore only shows up when you directly search for it, because it isn't even in the artist's list of albums.

### ViTune version

v1.0.5

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I am using a Google Pixel 6 Pro on Android 14.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-06-12 19:36
Duplicate of #229

**Closed by 25huizengek1** 2024-06-12 19:36 UTC
Labels: bug
