### ISSUE TITLE
YouTube Music Account Login

### ISSUE THREAD

**Issue by 7leonardorodrigues** [25huizengek1/ViTune#611] opened 2024-12-07 06:33 UTC
## Feature request: 
Add YouTube Music Account Login, in order to sync our streaming data, playlists, library, etc. Piped is cool to have as an option, but it would be great if we had an official YouTube option for those of us with premium, that just want a better UI than the stock app.

**Comment by Wqttzicue** [comment] 2024-12-07 08:07
It is thousandth suggestion of logging with YTM, as i understood, it wont happen.

**Comment by 25huizengek1** [comment] 2024-12-08 21:48
Duplicate of #199

**Closed by 25huizengek1** 2024-12-08 21:48 UTC
Labels: enhancement
