### ISSUE TITLE
The returned video ID doesnt match the requested one

### ISSUE THREAD

**Issue by Kimiberlianoputra** [25huizengek1/ViTune#509] opened 2024-10-24 23:26 UTC
### Steps to reproduce the bug

1. Select any music

### Expected behavior

Music play

### Actual behavior

The returned video ID doesnt match the requested one

### Screenshots/Screen recordings

![Screenshot_20241025_072306](https://github.com/user-attachments/assets/808a0086-ce7a-4cf8-b695-51a443040e70)

### ViTune version

v1.1.0

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14

### Device info

I am using samsung A15, running one ui

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-10-24 23:35
Duplicate of #499

**Closed by 25huizengek1** 2024-10-24 23:35 UTC
Labels: bug
