### ISSUE TITLE
Some song are not playing & show "The returned video ID doesn't match the requested one"

### ISSUE THREAD

**Issue by prtbws** [25huizengek1/ViTune#489] opened 2024-10-20 19:45 UTC
### Steps to reproduce the bug

It showing -- The returned video ID doesn't match the requested one

![Screenshot_20241021-010818](https://github.com/user-attachments/assets/f1a6fa97-4e91-4b29-af37-e4f4d9037980)

### Expected behavior

The music should palay !

### Actual behavior

It is not playing 
![1000026478](https://github.com/user-attachments/assets/7e2522b4-9920-48d3-9c4c-51db63e806be)

### ViTune version

Latest 

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

13

### Device info

Lava blaze 5g

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by Wqttzicue** [comment] 2024-10-21 09:18
1,000,002 issue about this, Are you really sure about  originality of issue, i assume you dont.

**Comment by 25huizengek1** [comment] 2024-10-21 22:09
Duplicate of (e.g.) #477

**Closed by 25huizengek1** 2024-10-21 22:09 UTC
Labels: bug
