### ISSUE TITLE
Local files are being shown even when they are deleted or don't exist

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViTune#231] opened 2024-04-12 04:10 UTC
### Steps to reproduce the bug

-Delete any audio file from your local storage
-Open ViTune

### Expected behavior

Audio file should dissapear from the list

### Actual behavior

Audio files are still present even when they don't exist anymore

### Screenshots/Screen recordings

![image](https://github.com/25huizengek1/ViTune/assets/1917871/8e2ec3dc-edcb-4e2e-9291-717931604080)

### ViTune version

1.0.1

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

Using Pixel 3a XL running Android 10

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)

**Comment by 25huizengek1** [comment] 2024-04-12 11:39
Duplicate of #163.

**Closed by 25huizengek1** 2024-04-12 11:39 UTC
Labels: bug
