### ISSUE TITLE
Gratitude and some features request 

### ISSUE THREAD

**Issue by Logan7899** [25huizengek1/ViTune#390] opened 2024-07-15 10:06 UTC
Thank u dev for this app. This is the best alternative to ViMusic with additional features. Keep it up. I want to add some features to be added if u like them:
1. Song time in modern player layout as it is missing.
2. Add an download button, the thing it will do to download specific songs not all the song that we listen not covering up the storage.
3. Add gms account which will improve the songs suggestion and inport our features.
4. To notify all the new songs and albums of the artist that we saved in vitune.
5. Add an option to keep mini player minimized when we tap on a song.

Some optional features:
1. Addition of Spotify canvas.
2. Add an option to play videos instead of audio with sponsorblock and return.

I hope u will like my feature request 😁

**Comment by 25huizengek1** [comment] 2024-07-15 11:30
Thank you, some feedback:

1. Already exists
2. Already exists
3. Duplicate of #199
4. Not possible, YouTube Music doesn't provide that kind of information. The in-app notifications are provided through FCM, which is something that ViTune cannot access.
5. Duplicate of #255

1. ViTune doesn't use Spotify data, I don't understand?
2. You can play videos, I guess adding sponsorblock is a good idea.

---

Moving to a separate issue.

**Closed** 2024-07-15 11:31 UTC
Labels: enhancement

**Comment by Logan7899** [comment] 2024-07-15 12:14
> Thank you, some feedback:
> 
> 1. Already exists
> 2. Already exists
> 3. Duplicate of [[Feature Request] Ability to refresh and login with google #199](https://github.com/25huizengek1/ViTune/issues/199)
> 4. Not possible, YouTube Music doesn't provide that kind of information. The in-app notifications are provided through FCM, which is something that ViTune cannot access.
> 5. Duplicate of [Initial Expressions and some changes #255](https://github.com/25huizengek1/ViTune/issues/255)
> 6. ViTune doesn't use Spotify data, I don't understand?
> 7. You can play videos, I guess adding sponsorblock is a good idea.
> 
> Moving to a separate issue.

 4.But in simp music it works
6. See we can log into our spotify account which will fetch the data and show us the canvas in the background

**Comment by 25huizengek1** [comment] 2024-07-15 14:15
4. Simp Music fetches all releases and notifies when it finds a new one. Not only will this eventually trigger YouTubes bot detection mechanisms, but it's also not reliable (YouTube doesn't guarantee that a song is always new, a simple album art change could mean a new video id on YouTube). It also uses a lot of battery, as the app has to fetch from YouTube even when the app is closed.

6. We'll keep ViTune for use with YouTube, for now. Maybe I'll add an import functionality for Spotify playlists but I won't hack together a solution for 'merging' data from YouTube with data from Spotify, at least for now.
