### ISSUE TITLE
Add Reorder Feature to Favorites Playlist

### ISSUE THREAD

**Issue by Mathew-88** [25huizengek1/ViTune#473] opened 2024-10-14 12:58 UTC
## Feature request: Add Reorder Feature to Favorites Playlist

Just like any other playlist, can it be made so that the "Favorites" playlist can be rearranged/reordered? May I ask why it hasn't been made like that?

It's honestly hard for me cause I use Favorites as my main playlist, anddd when I add a new song, it's on top of songs I don't plan to play (yes, I'm a dumdum, kinda) :'), so please add the feature. 

Edit: Maybe add an option to disable/enable reordering of the Favorites Playlist? (for those that don't want it)

Thanks!

**Comment by 25huizengek1** [comment] 2024-10-16 20:34
Duplicate of #401

**Closed by 25huizengek1** 2024-10-16 20:34 UTC
Labels: enhancement
