### ISSUE TITLE
recent I'm facing this issues that I can't able to play a song if I try to play it means it's showing [The returned video ID doesn't match
the requested one] will the song is play...in-between the song stop and it shows [The returned video ID doesn't match
the requested one] please fix the issues as soon as possible ...I want this app with no bugs and problems 

### ISSUE THREAD

**Issue by farookhamdan** [25huizengek1/ViTune#505] opened 2024-10-24 16:33 UTC
## Feature request: ...

A clear and concise description of the feature you want to request.

**Comment by MLGHerobrine** [comment] 2024-10-24 17:04
Piped API is down, please wait. This is also a duplicate issue.

**Comment by 25huizengek1** [comment] 2024-10-24 18:03
Duplicate of #499

**Closed by 25huizengek1** 2024-10-24 18:03 UTC
Labels: enhancement

**Comment by Wqttzicue** [comment] 2024-10-24 18:50
Stop spamming this issue, can u just google "ViTune [issue]" instead?
