### ISSUE TITLE
Resume playback with Bluetooth device not working

### ISSUE THREAD

**Issue by ardumiguel** [25huizengek1/ViTune#89] opened 2024-01-24 19:40 UTC
### Steps to reproduce the bug

Pause playback
Connect Bluetooth device

### Expected behavior

Pause playback
Connect Bluetooth device
Playback resumes

### Actual behavior

Playback doesn't resume.

Tried with two different Bluetooth devices.

Interestingly enough playback resumes after toggling the mentioned option, so I'd dare to say this has something to do with this other issue #68 as I've found the same situation (toggling option solves bug) with other options.

### ViMusic version

v.6.0.3

### Android version

Android 14

**Comment by 25huizengek1** [comment] 2024-01-24 21:47
Can't reproduce unfortunately. Do you have any logs or other context to this? A few things come to mind:

- What device are you using? Does it run an official (Google or vendor) Android build?
- What kind of bluetooth device are you using?
- Are you using a release build or nightly?
- Can you provide a screen recording of the issues you are experiencing?
- Could you please try this with today's (will be released in less than an hour) nightly build?

Thank you in advance. I'll try and get back with you while I investigate.

**Comment by ardumiguel** [comment] 2024-01-24 21:57
I'll get to you with some further testing on the latest nightly version ASAP as well as some info about my system.

**Comment by ardumiguel** [comment] 2024-01-27 16:47
Thank you for your attention dev. It seems like it was a bug of my device. Still doing further testing

**Comment by 25huizengek1** [comment] 2024-01-27 22:50
No problem. Please let me know if you find anything.

**Comment by dtomvan** [comment] 2024-02-05 09:46
I also have a suggestion to further examine this issue: could you try different Bluetooth devices and/or apps which have a similar feature? This could prove the issue lies with ViMusic specifically.

**Comment by 25huizengek1** [comment] 2024-02-08 07:54
Any updates on this?

**Comment by ardumiguel** [comment] 2024-02-10 23:07
> Any updates on this?

Been busy lately and haven't had time to do further testing but I'm still on it.

**Closed** 2024-03-14 16:37 UTC
Labels: bug
