### ISSUE TITLE
Release on f-droid official repository

### ISSUE THREAD

**Issue by tvnmguy** [25huizengek1/ViTune#358] opened 2024-06-19 01:22 UTC
https://f-droid.org/contribute/

**Comment by Enigma1309** [comment] 2024-06-19 07:38
that would be nice but this app breaks the google tos and probably wont be allowed on official fdroid repo but i this this app can be added to izzyOnDroid repo 

see this too https://github.com/25huizengek1/ViTune/discussions/217

**Comment by 25huizengek1** [comment] 2024-06-20 18:02
Duplicate of #217

**Closed by 25huizengek1** 2024-06-20 18:02 UTC
