### ISSUE TITLE
Make an option for YouTube sign in

### ISSUE THREAD

**Issue by MRW-K01** [25huizengek1/ViTune#563] opened 2024-11-13 10:49 UTC
## Feature request: ...

A clear and concise description of the feature you want to request.

**Comment by Wqttzicue** [comment] 2024-11-14 07:33
Already suggested. This **WON'T** happen

**Comment by MRW-K01** [comment] 2024-11-16 13:55
But why, it enable yt client to accessible

**Comment by Wqttzicue** [comment] 2024-11-16 14:19
> But why, it enable yt client to accessible 
> 

This will require google sign in, so it means working with Youtube API and it means ads, loss of provacy and all that kind of stuff (as i understood, im not computernerd enough)

**Comment by sidsharths1245** [comment] 2024-11-19 05:55
What if we use microg instead?

**Comment by Wqttzicue** [comment] 2024-11-19 10:03
> What if we use microg instead? Like revanced youtube music does

MicroG dont have syncs with Piped Api
You cant really replace Piped Api

**Comment by 25huizengek1** [comment] 2024-11-20 20:57
Duplicate of #199

**Closed by 25huizengek1** 2024-11-20 20:57 UTC
Labels: enhancement
