### ISSUE TITLE
Importing CSV/JSON databse for Spotify Music

### ISSUE THREAD

**Issue by rishi0810** [25huizengek1/ViTune#598] opened 2024-11-29 07:19 UTC
Currently Vitunes allows importing CSV file from local storage but for the average consumer, converting their Spotify playlist to a CSV is probably too tiresome as it involves third party application like Tunemymusic and such
And an increase in userbase is expected following the server side api restrictions due to which mods are discontinued, so there should be system which converts a user's Spotify playlists/content to vitunes within the application itself

**Comment by 25huizengek1** [comment] 2024-12-01 11:55
Duplicate of #172

**Closed by 25huizengek1** 2024-12-01 11:55 UTC
Labels: enhancement
